<?php
$nomina = array(
"altar"=>array("8","altar","","aris, n. : l'autel"),
"altare"=>array("8","altar","","is, n. : autel"),
"ancilia"=>array("8","ancil","","ium, n. : le bouclier sacré (tombé du ciel sous le règne de Numa : il en fit faire onze semblables qui furent confiés à la garde des prêtres Saliens)"),
"animal"=>array("8","animal","","alis, n. : être vivant, animal"),
"augurale"=>array("8","augural","","is, n. : l'augural (partie droite de la tente d'un général où il prend les auspices)"),
"Bacchanalia"=>array("8","Bacchanal","","ium, n. : les Bacchanales (fêtes de Bacchus)"),
"bouile"=>array("8","","","is, n. : étable"),
"calcar"=>array("8","calcar","","aris, n. : l'éperon"),
"capital"=>array("8","capital","","alis, n. : le crime capital"),
"ceruical"=>array("8","ceruical","","alis, n. : l'oreiller, le coussin"),
"collare"=>array("8","collar","","is, n. : collier"),
"conclaue"=>array("8","conclau","","is, n. : la chambre (à coucher), la salle à manger"),
"cubile"=>array("8","cubil","","is, n. : lit, couche"),
"equile"=>array("8","equil","","is, n. : écurie"),
"exemplar"=>array("8","","","aris, n. : copie, exemplaire"),
"funale"=>array("8","funal","","is, n : la torche"),
"hastile"=>array("8","hastil","","is, n. : le bois d'un javelot"),
"lacunar"=>array("8","lacunar","","aris, n. : le plafond"),
"laquearia"=>array("8","laquear","","ium, n. : le plafond lambrissé, le lambris"),
"mare"=>array("8","mar","","is, n. : mer"),
"mille"=>array("8","mill","","n.   pl. ia, ium : mille (milia : quand il s'agit de plusieurs milliers)"),
"moenia"=>array("8","moen","","ium, n. : les murs, les murailles"),
"monile"=>array("8","monil","","is, n. : collier, bijoux, joyaux"),
"penetrale"=>array("8","penetra","","l'endroit le plus reculé"),
"praesaepe"=>array("8","praesaep","","is, n. : étable, écurie, salle à manger"),
"rete"=>array("8","ret","","is, n. : filet, piège"),
"sedile"=>array("8","sedil","","is, n. : le siège, le banc,  le repos sur un siège"),
"sollemne"=>array("8","sollemn","","is, n. : la solennité, la fête, la cérémonie"),
"talaria"=>array("8","","",", talarium, n. : chevilles"),
"talaris"=>array("8","talar","",", talarium, n. : chevilles"),
"tribunal"=>array("8","tribunal","","alis, n. : le tribunal"),
"uectigal"=>array("8","uectigal","","alis, n. : l'impôt"),
"utensilia"=>array("8","utensil","","ium, n. : tout ce qui est utile à nos besoins;  les moyens d'existence"),
);
?>
