# Generated by Django 2.2.24 on 2021-07-20 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('summary', models.TextField(blank=True)),
                ('url', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gaffiot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=20)),
                ('latine', models.CharField(max_length=255)),
                ('gallice', models.CharField(max_length=255)),
                ('genitif', models.CharField(default='', max_length=255)),
                ('genre', models.CharField(default='m', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LogRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('record', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('summary', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorksheetContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crustula.Exercise')),
                ('ws', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crustula.Worksheet')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.FloatField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crustula.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Ov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latine', models.CharField(max_length=255, unique=True)),
                ('gallice', models.CharField(default='<nominatif>/', max_length=255)),
                ('genre', models.CharField(default='m', max_length=1)),
                ('sovs', models.ManyToManyField(to='crustula.Sov')),
            ],
        ),
    ]
