# Generated by Django 2.2.24 on 2021-07-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crustula', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gaffiot',
            old_name='galle',
            new_name='gallice',
        ),
    ]
