# Generated by Django 2.2.24 on 2021-07-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crustula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latine', models.CharField(max_length=255, unique=True)),
                ('gallice', models.CharField(default='<singulier>/<pluriel>', max_length=255)),
                ('genre', models.CharField(default='m', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Uerbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latine', models.CharField(max_length=255, unique=True)),
                ('gallice', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
