# Generated by Django 2.2.24 on 2021-07-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crustula', '0002_auto_20210702_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaffiot',
            name='genitif',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='gaffiot',
            name='genre',
            field=models.CharField(default='m', max_length=255),
        ),
    ]
