# Generated by Django 2.2.24 on 2021-07-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crustula', '0003_auto_20210718_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latine', models.CharField(max_length=255)),
                ('gallice', models.CharField(max_length=255)),
                ('sovs', models.ManyToManyField(to='crustula.Sov')),
            ],
        ),
    ]
