# Generated by Django 2.2.24 on 2021-07-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crustula', '0004_ov_sov'),
    ]

    operations = [
        migrations.AddField(
            model_name='ov',
            name='genre',
            field=models.CharField(default='m', max_length=1),
            preserve_default=False,
        ),
    ]
