<?php
$titre='Adjectifs, classe de troisième';

$bini = array(
    array("augustus","","bonus","a, um : sacré, majestueux"),
    array("bonus","","bonus","a, um : bon. pl. neutre : les biens"),
    array("clarus","","bonus","a, um : célèbre"),
    array("dignus","","bonus","a, um : digne ; - + abl. : digne de qqch ; - qui + subj. : digne de..."),
    array("diuus","","bonus","a, um : divin"),
    array("felix","felic","uetus","icis, heureux"),
    array("fortis","fort","fortis","e : fort, vigoureux, courageux,"),
    array("magnus","","bonus","a, um : grand"),
    array("malus","","bonus","a, um : mauvais. comp. peior, sup. : pessimus (-umus)"),
    array("meus","","bonus","mea, meum : mon"),
    array("multi","","bonus","ae, a : (de) nombreux"),
    array("omnis","omn","fortis","e : tout"),
    array("optimus","","bonus","a, um : très bon, le meilleur. superlatif de bonus"),
    array("pauci","","bonus","ae, a : pl. peu de"),
    array("pius","","bonus","a, um : pieux, juste"),
    array("pulcher","","pulcher","chra, chrum : beau"),
    array("sacer","","pulcher","cra, crum : sacré"),
    array("sanctus","","bonus","a, um : sacré, saint"),
    array("tuus","","bonus","a, um : ton"),
    array("aequalis","aequal","fortis","e : du même âge"),
    array("alienus","","bonus","a, um : d'autrui, étranger, éloigné, déplacé, désavantageux"),
    array("altus","","bonus","a, um : haut, profond, grand (métaph.)"),
    array("audax","audac","fortis","acis : audacieux"),
    array("auarus","","amicus","a, um avare, avide, cupide"),
    array("auidus","","bonus","a, um : désireux, avide"),
    array("barbarus","","bonus","a, um : barbare"),
    array("beatus","","bonus","a, um : heureux"),
    array("benignus","","bonus","a, um : bienveillant"),
    array("breuis","breu","fortis","e : court (espace ou temps)"),
    array("carus","","bonus","a, um : cher"),
    array("celer","celer","acer","eris, ere : rapide"),
    array("certus","","bonus","a, um : certain"),
    array("ceteri","","bonus","ae, a : pl. tous les autres"),
    array("crudelis","crudel","fortis","e : cruel"),
    array("decem","","inv","adj. num. : dix"),
    array("difficilis","difficil","fortis","e : difficile"),
    array("dissimilis","dissimil","fortis","e : différent"),
    array("diuersus","","bonus","a, um : allant dans des directions opposées, opposé"),
    array("diues","diuit","uetus","itis : riche"),
    array("dulcis","dulc","fortis","e : doux"),
    array("duo","","bonus","ae, o : deux"),
    array("durus","","bonus","a, um : dur"),
    array("egregius","","bonus","a, um : distingué, remarquable"),
    array("facilis","facil","fortis","e : facile"),
    array("falsus","","bonus","a, um : faux"),
    array("fessus","","bonus","a, um : fatigué"),
    array("fidelis","fidel","fortis","e : en qui l'on peut avoir confiance, sûr, fidèle"),
    array("gratus","","bonus","a, um : agréable, reconnaissant"),
    array("grauis","grau","fortis","e : sérieux, triste, lourd"),
    array("honestus","","bonus","a, um : honnête"),
    array("humanus","","bonus","a, um : humain"),
    array("impar","impar","fortis","aris : inégal"),
    array("impiger","","pulcher","gra, grum : actif, rapide"),
    array("improbus","","bonus","a, um : malhonnête"),
    array("imus","","bonus","a, um : le plus profond de, le fond de"),
    array("ingens","ingent","fortis","entis : immense, énorme"),
    array("iratus","","bonus","a, um : en colère, irrité"),
    array("iucundus","","bonus","a, um : agréable"),
    array("laetus","","bonus","a, um : joyeux, agréable, favorable, abondant"),
    array("lentus","","bonus","a, um : souple, mou, apathique, indolent, impassible"),
    array("leuis","leu","fortis","e : léger"),
    array("liber","","miser","era, erum : libre"),
    array("longus","","bonus","a, um : long"),
    array("medius","","bonus","a, um : qui est au milieu, en son milieu"),
    array("mille","mill","mare","n. pl. ia, ium : mille"),
    array("miser","","miser","a, um : malheureux"),
    array("nobilis","nobil","fortis","e : connu, noble"),
    array("noster","nostr","pulcher","tra, trum : notre"),
    array("nouem","","invaria","inv. : neuf"),
    array("nouus","","bonus","a, um : nouveau"),
    array("octo","","invaria","adj. num. inv. : huit"),
    array("otiosus","","bonus","a, um : oisif, neutre, indifférent, calme"),
    array("par","par","fortis","aris : semblable, pareil"),
    array("patricius","","bonus","a, um : patricien, noble"),
    array("pauper","pauper","uetus","eris : pauvre"),
    array("perfidus","","bonus","a, um : perfide, sans foi"),
    array("piger","","pulcher","gra, grum : paresseux, grimaçant"),
    array("plenus","","bonus","a, um : plein, entier, complet"),
    array("plerique","","bonus","aeque, aque : la plupart"),
    array("primus","","bonus","a, um : premier (comparatif : prior)"),
    array("probus","","bonus","a, um : honnête. La première lettre est p"),
    array("propinquus","","bonus","a, um : proche"),
    array("propior","propior","uetus","oris : plus proche"),
    array("proximus","","bonus","a, um : proche ; primus... - : le 1er... le second"),
    array("quatuor","","inv","inv. : quatre"),
    array("quinque","","inv","adj. inv. : cinq"),
    array("saeuus","","bonus","a, um : cruel"),
    array("secundus","","bonus","a, um : second, favorable"),
    array("securus","","bonus","a, um : sans soucis, tranquille, sûr"),
    array("septem","","invaria","adj. num. : sept"),
    array("sex","","invaria","adj. num. : six"),
    array("solus","","bonus","a, um : seul"),
    array("summus","","bonus","a, um : élevé, qui est en haut, supérieur"),
    array("superbus","","bonus","a, um : orgueilleux"),
    array("superus","","bonus","a, um : qui est au dessus ; avec majuscule : les dieux"),
    array("suus","","bonus","a, um : adj. : son, sa"),
    array("tertius","","bonus","a, um : troisième"),
    array("totus","","bonus","a, um : tout entier"),
    array("tres","tr","fortis","ium : trois"),
    array("tristis","trist","fortis","e : triste, sombre, sévère, morose"),
    array("turpis","turp","fortis","e : honteux"),
    array("tutus","","bonus","a, um : protégé, en sécurité, sûr"),
    array("unus","","bonus","a, um : un seul, un"),
    array("ualidus","","bonus","a, um : bien portant, fort, solide ; agissant, efficace, puissant"),
    array("uastus","","bonus","a, um : vide, désert, désolé, vaste"),
    array("uelox","","fortis","ocis : rapide"),
    array("uester","","pulcher","tra, trum : votre"),
    array("uetus","ueter","uetus","ueteris : vieux"),
    array("acer","acr","acer","cris, cre : aigu, tranchant, perçant, vif, subtil, énergique"),
    array("acerbus","","bonus","a, um : pénible, désagréable"),
    array("acutus","","bonus","a, um : aigu, vif, piquant"),
    array("aequus","","bonus","a, um : égal, équitable"),
    array("amplus","","bonus","a, um : grand, important"),
    array("antiquus","","bonus","a, um : ancien"),
    array("aptus","apt","bonus","a, um : attaché à, apte"),
    array("asper","","miser","era, erum : âpre, sévère, rude"),
    array("blandus","","bonus","a, um : caressant, câlin, flatteur, attrayant, séduisant"),
    array("calidus","","bonus","a, um : chaud"),
    array("candidus","","bonus","a, um : blanc"),
    array("celeber","celebr","acer","bris, bre : en grand nombre, très fréquenté"),
    array("ciuilis","ciuil","fortis","e : civil"),
    array("conscius","","bonus","a, um : qui sait avec d'autres, confident, témoin, complice, conscient de"),
    array("copiosus","","bonus","a, um : riche. La première lettre est c"),
    array("creber","","pulcher","bra, brum : fréquent. pl. nombreux"),
    array("disertus","","bonus","a, um : éloquent, expressif"),
    array("dubius","","bonus","a, um : douteux"),
    array("eruditus","","bonus","a, um : instruit, formé, expérimenté, savant"),
    array("humilis","humil","fortis","e : humble, pauvre"),
    array("ignarus","","bonus","a, um :  qui ne connaît pas, ignorant, inconnu. La première lettre est i"),
    array("immanis","imman","fortis","e : monstrueux, énorme"),
    array("ingeniosus","","bonus","a, um : intelligent, ingénieux, adroit"),
    array("insignis","insign","fortis","e : qui a un signe particulier, reconnaissable, remarquable, distingué "),
    array("integer","","pulcher","gra, grum : non touché, sain et sauf"),
    array("lenis","len","fortis","e : doux. la première lettre est l"),
    array("liberalis","","fortis","e : noble, libéral, généreux"),
    array("maestus","","bonus","a, um : triste"),
    array("mollis","moll","fortis","e : mou, fluide, souple, flexible"),
    array("memor","memor","uetus","oris, +gén. : qui a le souvenir"),
    array("mirus","","bonus","a, um : étonnant"),
    array("necessarius","","bonus","a, um : nécessaire, lié par l'amitié"),
    array("nescius","","bonus","a, um : qui ne sait pas, ignorant. La première lettre est n"),
    array("notus","","bonus","a, um : connu, fameux, familier"),
    array("peritus","","bonus","a, um : expert, savant, connaisseur"),
    array("placidus","","bonus","a, um : doux, calme, paisible"),
    array("popularis","popular","fortis","e : qui a trait au peuple, compatriote"),
    array("potens","potent","fortis","entis : puissant"),
    array("prudens","prudent","fortis","entis : sage, prévoyant"),
    array("publicus","","bonus","a, um : public"),
    array("rectus","","bonus","a, um : droit, correct"),
    array("rudis","rud","fortis","e : brut, inculte"),
    array("sapiens","sapient","fortis","entis : sage"),
    array("similis","simil","fortis","e : semblable"),
    array("sollers","sollert","fortis","ertis : habile, adroit, ingénieux, intelligent"),
    array("sollicitus","","bonus","a, um : inquiet, soucieux"),
    array("suauis","suau","fortis","e : doux, agréable, suave"),
    array("supplex","","fortis","plicis : suppliant"),
    array("tacitus","","bonus","a, um : tacite, muet"),
    array("tener","","miser","era, erum : tendre"),
    array("tenuis","tenu","fortis","e : mince, fin, léger, faible ; subtil, délicat; misérable, pauvre"),
    array("uber","uber","acer","fertile, fécond"),
    array("urbanus","","bonus","a, um : urbain, poli, spirituel, fin"),
    array("utilis","util","fortis","e : utile"),
    array("uarius","uarietat","bonus","a, um : varié, divers")
);
?>
