<?php
$titre='Adjectifs, classe de quatrième';
$bini=array(
    array("augustus","","bonus","a, um : sacré, majestueux"),
    array("bonus","","bonus","a, um : bon. pl. neutre : les biens"),
    array("clarus","","bonus","a, um : célèbre"),
    array("dignus","","bonus","a, um : digne ; - + abl. : digne de qqch ; - qui + subj. : digne de..."),
    array("diuus","","bonus","a, um : divin"),
    array("felix","felic","uetus","icis, heureux"),
    array("fortis","fort","fortis","e : fort, vigoureux, courageux,"),
    array("magnus","","bonus","a, um : grand"),
    array("malus","","bonus","a, um : mauvais. comp. peior, sup. : pessimus (-umus)"),
    array("meus","","bonus","mea, meum : mon"),
    array("multi","","bonus","ae, a : (de) nombreux"),
    array("omnis","omn","fortis","e : tout"),
    array("optimus","","bonus","a, um : très bon, le meilleur. superlatif de bonus"),
    array("pauci","","bonus","ae, a : pl. peu de"),
    array("pius","","bonus","a, um : pieux, juste"),
    array("pulcher","","pulcher","chra, chrum : beau"),
    array("sacer","","pulcher","cra, crum : sacré"),
    array("sanctus","","bonus","a, um : sacré, saint"),
    array("tuus","","bonus","a, um : ton"),
    array("aequalis","aequal","fortis","e : du même âge"),
    array("alienus","","bonus","a, um : d'autrui, étranger, éloigné, déplacé, désavantageux"),
    array("altus","","bonus","a, um : haut, profond, grand (métaph.)"),
    array("audax","audac","fortis","acis : audacieux"),
    array("auarus","","amicus","a, um : avare, avide, cupide"),
    array("auidus","","bonus","a, um : désireux, avide"),
    array("barbarus","","bonus","a, um : barbare"),
    array("beatus","","bonus","a, um : heureux"),
    array("benignus","","bonus","a, um : bienveillant"),
    array("breuis","breu","fortis","e : court (espace ou temps)"),
    array("carus","","bonus","a, um : cher"),
    array("celer","celer","acer","eris, ere : rapide"),
    array("certus","","bonus","a, um : certain"),
    array("ceteri","","bonus","ae, a : pl. tous les autres"),
    array("crudelis","crudel","fortis","e : cruel"),
    array("decem","","inv","adj. num. : dix"),
    array("difficilis","difficil","fortis","e : difficile"),
    array("diuersus","","bonus","a, um : allant dans des directions opposées, opposé"),
    array("diues","diuit","uetus","itis : riche"),
    array("dulcis","dulc","fortis","e : doux"),
    array("duo","","bonus","ae, o : deux"),
    array("durus","","bonus","a, um : dur"),
    array("egregius","","bonus","a, um : distingué, remarquable"),
    array("facilis","facil","fortis","e : facile"),
    array("falsus","","bonus","a, um : faux"),
    array("fessus","","bonus","a, um : fatigué"),
    array("fidelis","fidel","fortis","e : en qui l'on peut avoir confiance, sûr, fidèle"),
    array("gratus","","bonus","a, um : agréable, reconnaissant"),
    array("grauis","grau","fortis","e : sérieux, triste, lourd"),
    array("honestus","","bonus","a, um : honnête"),
    array("humanus","","bonus","a, um : humain"),
    array("impar","impar","fortis","aris : inégal"),
    array("impiger","","pulcher","gra, grum : actif, rapide"),
    array("improbus","","bonus","a, um : malhonnête"),
    array("imus","","bonus","a, um : le plus profond de, le fond de"),
    array("ingens","ingent","fortis","entis : immense, énorme"),
    array("iratus","","bonus","a, um : en colère, irrité"),
    array("laetus","","bonus","a, um : joyeux, agréable, favorable, abondant"),
    array("lentus","","bonus","a, um : souple, mou, apathique, indolent, impassible"),
    array("leuis","leu","fortis","e : léger"),
    array("liber","","miser","era, erum : libre"),
    array("longus","","bonus","a, um : long"),
    array("medius","","bonus","a, um : qui est au milieu, en son milieu"),
    array("mille","mill","mare","n. pl. ia, ium : mille"),
    array("miser","","miser","a, um : malheureux"),
    array("nobilis","nobil","fortis","e : connu, noble"),
    array("noster","nostr","pulcher","tra, trum : notre"),
    array("nouem","","invaria","inv. : neuf"),
    array("nouus","","bonus","a, um : nouveau"),
    array("octo","","invaria","adj. num. inv. : huit"),
    array("otiosus","","bonus","a, um : oisif, neutre, indifférent, calme"),
    array("par","par","fortis","aris : semblable, pareil"),
    array("patricius","","bonus","a, um : patricien, noble"),
    array("pauper","pauper","uetus","eris : pauvre"),
    array("perfidus","","bonus","a, um : perfide, sans foi"),
    array("piger","","pulcher","gra, grum : paresseux, grimaçant"),
    array("plenus","","bonus","a, um : plein, entier, complet"),
    array("plerique","","bonus","aeque, aque : la plupart"),
    array("primus","","bonus","a, um : premier (comparatif : prior)"),
    array("probus","","bonus","a, um : honnête. La première lettre est p"),
    array("propinquus","","bonus","a, um : proche"),
    array("propior","propior","uetus","oris : plus proche"),
    array("proximus","","bonus","a, um : proche ; primus... - : le 1er... le second"),
    array("quatuor","","inv","inv. : quatre"),
    array("quinque","","inv","adj. inv. : cinq"),
    array("saeuus","","bonus","a, um : cruel"),
    array("secundus","","bonus","a, um : second, favorable"),
    array("securus","","bonus","a, um : sans soucis, tranquille, sûr"),
    array("septem","","invaria","adj. num. : sept"),
    array("sex","","invaria","adj. num. : six"),
    array("solus","","bonus","a, um : seul"),
    array("summus","","bonus","a, um : élevé, qui est en haut, supérieur"),
    array("superbus","","bonus","a, um : orgueilleux"),
    array("superus","","bonus","a, um : qui est au dessus ; avec majuscule : les dieux"),
    array("suus","","bonus","a, um : adj. : son, sa"),
    array("tertius","","bonus","a, um : troisième"),
    array("totus","","bonus","a, um : tout entier"),
    array("tres","tr","fortis","ium : trois"),
    array("tristis","trist","fortis","e : triste, sombre, sévère, morose"),
    array("turpis","turp","fortis","e : honteux"),
    array("tutus","","bonus","a, um : protégé, en sécurité, sûr"),
    array("unus","","bonus","a, um : un seul, un"),
    array("ualidus","","bonus","a, um : bien portant, fort, solide ; agissant, efficace, puissant"),
    array("uastus","","bonus","a, um : vide, désert, désolé, vaste"),
    array("uelox","","fortis","ocis : rapide"),
    array("uester","","pulcher","tra, trum : votre"),
    array("uetus","ueter","uetus","ueteris : vieux")
);
?>
