<?php
$titre = 'Adverbes à savoir en fin de troisième';
$bini = array(
    array("deinde","ensuite"),
    array("iam","déjà, à l'instant"),
    array("nunc","maintenant"),
    array("saepe","souvent"),
    array("semper","toujours"),
    array("tum","alors. Dernière lettre : m"),
    array("diu","longtemps"),
    array("denique","enfin. Première lettre : d"),
    array("etiam","encore, en plus, aussi, même, bien plus"),
    array("magis","plus"),
    array("modo","seulement ; naguère, il y a peu (-... -... tantôt... tantôt...)"),
    array("multum","beaucoup"),
    array("mox","bientôt"),
    array("-ne","est-ce que (se colle à la fin d'un mot)"),
    array("nimis","trop"),
    array("nonne","est-ce que... ne... pas ?"),
    array("num","est-ce que par hasard, est-ce que"),
    array("primum","d'abord, pour la première fois"),
    array("qua","par là (lieu par où l'on passe)"),
    array("quo","où (lieu où l'on va)"),
    array("satis","assez, suffisamment"),
    array("simul","en même temps"),
    array("tam","si, autant"),
    array("tantum","tant de, tellement ; seulement"),
    array("tot","tant, si nombreux"),
    array("tunc","alors. Dernière lettre : c"),
    array("ubi","où (lieu où l'on est)"),
    array("unde","d'où"),
    array("adeo","tellement ; -... ut + subj tellement... que"),
    array("certe","certainement, sûrement. Première lettre : c"),
    array("ceterum","du reste"),
    array("diligenter","attentivement, scrupuleusement"),
    array("equidem","bien sûr, évidemment"),
    array("frustra","en vain"),
    array("immo","pas du tout, non, au contraire"),
    array("inde","de là, donc"),
    array("interea","entre-temps"),
    array("libenter","volontiers, avec plaisir"),
    array("paene","presque"),
    array("potius","plutôt"),
    array("procul","loin, au loin, de loin"),
    array("profecto","assurément, sûrement. Première lettre : p"),
    array("quidem","certes (ne -) ne pas même"),
    array("retro","en arrière, par derrière"),
    array("rursus","de nouveau, au contraire"),
    array("sane","vraiment, parfaitement. Première lettre : s"),
    array("scilicet","il va de soi, bien entendu"),
    array("statim","aussitôt"),
    array("tandem","enfin. Première lettre : t"),
    array("undique","de toutes parts, de tous côtés"),
    array("usque","continuellement"),
    array("utinam","pourvu que... !, si seulement... !"),
    array("utrum... an","est-ce que... ou est-ce que... ?"),
    array("uehementer","violemment, passionnément"),
    array("uix","à peine")
);
?>
