<?php
$lex = array(
array("amicus","amic","amicus","m","i, m. : ami"),
array("animus","anim","amicus","m","i, m. : coeur, sympathie, courage, esprit"),
array("annus","ann","amicus","m","i, m. : année"),
array("campus","camp","amicus","m","i, m. : plaine, champ"),
array("cibus","cib","amicus","m","i, m. : nourriture, repas, sève"),
array("deus","de","amicus","m","i, m. : le dieu"),
array("digitus","digit","amicus","m","i, m. : doigt"),
array("dolus","dol","amicus","m","i, m. : l'adresse, la ruse"),
array("dominus","domin","amicus","m","i, m. :maître"),
array("equus","equ","amicus","m","i, m. : cheval"),
array("filius","fili","amicus","m","ii, m. : fils"),
array("gladius","gladi","amicus","m","i, m. : glaive"),
array("humerus","humer","amicus","m","i, m. : épaule"),
array("humus","hum","amicus","f","i, f. : terre"),
array("lacertus","lacert","amicus","m","i, m. : muscle, bras"),
array("lectus","lect","amicus","m","i, m. : lit"),
array("legatus","legat","amicus","m","i, m. : légat, envoyé"),
array("locus","loc","amicus","m","i, m. : lieu, endroit, situation. Le pluriel est neutre"),
array("lucus","luc","amicus","m","i, m. : bois sacré"),
array("maritus","marit","amicus","m","i, m. : mari"),
array("modus","mod","amicus","m","i, m. : mesure, limite, manière"),
array("morbus","morb","amicus","m","i, m. : maladie"),
array("mundus","mund","amicus","m","i, m. : monde"),
array("murus","mur","amicus","m","i, m. : mur"),
array("necessarius","necessari","amicus","m","i, m. : parent, ami, allié"),
array("neruus","neru","amicus","m","i, m. : nerf"),
array("numerus","numer","amicus","m","i, m. : le nombre"),
array("oculus","ocul","amicus","m","i, m. : oeil"),
array("philosophus","philosoph","amicus","m","i, m. : philosophe"),
array("pontus","pont","amicus","m","i, m. : haute mer, mer"),
array("populus","popul","amicus","m","i, m. : peuple"),
array("praefectus","praefect","amicus","m","i, m. : gouverneur, administrateur"),
array("reus","re","amicus","m","i, m. : accusé"),
array("seruus","seru","amicus","m","i, m. : l'esclave"),
array("somnus","somn","amicus","m","i, m. : sommeil"),
array("taurus","taur","amicus","m","i, m. : taureau"),
array("torus","tor","amicus","m","i, m. : renflement, muscle saillant ; lit"),
array("tribunus","tribun","amicus","m","i, m. : tribun"),
array("uentus","uent","amicus","m","i, m. : vent"),
array("umerus","umer","amicus","m","i, m. : l'épaule"),
array("uulgus","uulg","amicus","n","i, n. : foule, le commun des hommes")
);
?>
