<?php
// cas1.php : Étude de la valeurs des cas ; constructions directes.
$bini = array(
// ablatif
  array("Bassus magna hominum -frequentia- exceptus est.",
        "Bassus fut reçu au milieu d'une grande -affluence- d'hommes.",
        "ablatif","frequentia, ae, f."),
  array("Nero fuit -ualetudine- prospera.","Néron avait une bonne -santé- (fut de santé heureuse).",
        "ablatif","ualetudo, dinis, f."),
  array("decorus erit tibi quaestor -patre- praetorio.","Un questeur de -père- prétorien te conviendra.",
        "ablatif","pater, tris, m."),
  array("canto carmina -uersibus- minutis.","Je chante des poèmes en -vers- menus.",
        "ablatif","uersus, us, m."),
  array("adulescens scissis tunicis sola uelatus -toga- perstitit.",
        "Un jeune homme, la tunique déchirée, resta, vêtu de sa seule -toge-.",
        "ablatif","toga, ae, f."),
  array("-iure- gratularis.","Tu as raison de me féliciter (tu me félicites avec -raison-).",
        "ablatif","ius, iuris, n."),
  array("Acta est causa -more- maiorum.","La cause a été plaidée à la -manière- des ancêtres.",
        "ablatif","mos, moris, m."),
  array("diem -epulo- celebrare constitui.","J'ai décidé de célébrer ce jour par -un banquet-.",
        "ablatif","epulum, i, n."),
  array("Conuenitur ad eum mira -celebritate-.","On accourt vers lui -avec une affluence- étonnante.",
        "ablatif","celebritas, atis, f."),
  array("uestimenta detracta sunt, -uirgis- caesus est.",
        "Ses vêtements lui furent ôtes, il fut battu de -verges-.",
        "ablatif","uirga, ae, f."),
  array("Virgarum -metu- Agyrinenses quod imperatum esset facturos se esse dixerunt.",
        "-Par peur- d'être fouettés, les Agyriens dirent qu'ils feraient ce qui avait été ordonné.",
        "ablatif","metus, us, m."),
  array("Cenabenses paulo ante mediam noctem -silentio- ex oppido egressi flumen transire coeperunt.",
        "Les Orléanais, sortis -en silence- de la place forte peu avant le milieu de la nuit, "
        ."commencèrent de traverser le fleuve.",
        "ablatif","silentium, ii, n."),
  array("Nam seueritatem istam pari -iucunditate- condire non minus difficile quam magnum est.",
        "Car tempérer cette gravité qui est la tienne par une égale -amabilité-, voilà qui n'est pas "
       ."moins difficile que grand.",
       "ablatif","iucunditas, atis, f."),
  array("fratremque optimum pari -caritate- diligis, filiamque eius",
        "Tu aimes -d'un amour- égal ton excellent frère et sa fille.",
        "ablatif","caritas, atis, f."),
  array("templum -pecunia- mea exstruxi.","J'ai construit un temple avec mon propre -argent-.",
        "ablatif","pecunia, ae, f."),
  array("-gloria- famaque ducuntur.","Ils sont conduits -par la gloire- et par la renommée.",
        "ablatif","gloria, ae, f."),
  array("incredibili -gaudio- sum elatus.","J'ai été pris d'une -joie- incroyable.",
        "ablatif","gaudium, ii, n."),
  array("falsi amici sereno vitae -tempore- praesto sunt; simul atque hiemem fortunae "
        ."viderunt, devolant omnes.",
        "Les faux amis s'offrent à nous -dans le temps- serein de la vie, s'enfuient dès "
        ."qu'ils ont vu l'hiver de la fortune.",
        "ablatif","pater, tris, m."),
  array("septem fuisse dicuntur uno -tempore-, qui sapientes et haberentur et vocarentur.",
        "Il y eut sept hommes, dit-on, qui étaient jugés et appelés sages à la même -époque-.",
              "ablatif","tempus, oris, n."),
  array("Vbique uitia -remediis- fortiora.","Partout les maux sont plus forts -que les remèdes-.",
        "ablatif","remedium, ii, n."),
  array("Tum consilio repente mutato Brundisium -terra- petere contendi.",
        "Alors, changeant soudain de plan, je me suis rendu à Brindes -par la terre-.",
        "ablatif","terra, ae, f."),
// nominatif        
  array("inveterauit enim iam -opinio- perniciosa.",
        "-Une opinion- funeste s'est déjà répandue",
        "nominatif","opinio, onis, f."),
  array("reus in iudicium adductus est C. -Verres-",
        "Caius -Verres- est cité en justice.",
        "nominatif","Verres, is, m."),
  array("multae mihi a C. Verre -insidiae- terra marique factae sunt",
        "Bien des -embûches- m'ont été tendues et sur terre et sur mer par C. Verrès.",
        "nominatif","insidiae, arum, f."),
  array("Nunc -homo- audacissimus atque amentissimus hoc cogitat.",
        "Et maintenant voici ce que fait -cet homme- audacieux, insensé.",
        "nominatif","homo, hominis, m."),
  array("Quibus -ego- rebus quid iste speret et quo animum intendat facile perspicio.",
        "Ce qu'il espère par là, quel est son but, -je- le vois facilement.",
        "nominatif","ego, mei, mf."),
  array("Nulla -res- per triennium, nisi ad nutum istius, iudicata est",
        "Aucune -affaire-, pendant trois ans, n'a été jugée autrement que selon son caprice",
        "nominatif","res, rei, f."),
  array("Idem iste -praetor- monumenta antiquissima spoliauit, nudauitque omnia.",
        "Ce même -préteur- a pillé et dépouillé tous les monuments les plus antiques.",
        "nominatif","praetor, oris, m."),
  array("iste -homo- amens ac perditus alia mecum ratione pugnat.",
        "cet -homme- insensé et pitoyable me combat, d'une autre manière.",
        "nominatif","homo, hominis, m."),
  array("Praeclare se -res- habebat.","-Son affaire- marchait à merveille.",
        "nominatif","res, rei, f."),
  array("Urgebant -comitia-.","-Les comices- étaient sur le point de commencer.",
        "nominatif","comitium, ii, n."),
  array("Arcessit alter -consul- designatus Siculos.",
        "Le second -consul- désigné fait venir les Siciliens.",
        "nominatif","consul, ulis, m."),
  array("tres hi, -homines- ueteres, [tribuni] militares sunt designati.",
        "Ces trois personnes, -hommes- dignes de nos anciens, furent nommées [tribuns] militaires.",
        "nominatif","homo, inis, m."),
  array("Erit tum -consul- Hortensius cum summo imperio et potestate.",
        "Hortensius sera alors -consul-, revêtu du commandemant suprême et des pleins pouvoirs.",
        "nominatif","consul, ulis, m."),
  array("tum uero non strepitu, sed maximo clamore, suam -populus- Romanus significauit uoluntatem.",
        "Alors, -le peuple- romain manifesta sa volonté nom par des murmures, mais en criant très fort.",
        "nominatif","populus, i, m."),
  array("Nunc autem -homines- in speculis sunt.","Or maintenant -les gens- sont aux aguets.",
        "nominatif","homo, hominis, m."),
  array("Circumstant te summae -auctoritates-.","Les plus hautes -autorités- t'entourent.",
        "nominatif","auctoritas, atis, f."),
  array("-Haec- primae actionis erit accusatio.",
        "L'accusation de cette première plaidoierie sera -celle~ci- :",
        "nominatif","hic, haec, hoc"),
  array("Ego primam tollo, nominor quia -leo-.","Je prends la première, parce que je m'appelle -le lion-.",
        "nominatif","leo, leonis, m."),
  array("Cur ego -poeta- salutor ?","Pourquoi suis-je appelé -poète- ?",
        "nominatif","poeta, ae, m."),
// vocatif        
  array("Etiam atque etiam, noster -Tiro-, vale.",
        "Adieu, et encore adieu, mon cher -Tiron-.",
        "vocatif","Tiro, onis, m."),
  array("Quam spem nunc habeat in manibus, et quid moliatur, breuiter iam, -iudices-, uobis exponam.",
        "Je vous exposerai bientôt brièvement, -juges-, quel espoir il a maintenant et ce qu'il médite.",
        "vocatif","iudex, icis, m."),
  array("Non amo te, -Sabidi-, nec possum dicere quare :<br>     Hoc tantum possum dicere, non amo te.",
        "Je ne t'aime pas, -Sabidius-, et je ne peux dire pourquoi.<br>     Je peux seulement dire cela :"
        ." Je ne t'aime pas.",
        "vocatif","Sabidius, ii, m."),
  array("Qualem, -Flacce-, uelim quaeris nolimue puellam ?",
        "Tu demandes, -Flaccus-, quelle petite amie je voudrais ou ne voudrais pas ?",
        "vocatif","Flaccus, i, m."),
  array("Ut recitem tibi nostra rogas epigrammata. Nolo." 
        ."<br>           Non audire, -Celer-, sed recitare cupis.",
        "Tu veux que je te déclame mes épigrammes. Je refuse."
        ."<br>           Tu ne veux pas écouter, -Celer-, tu veux déclamer.",
        "vocatif","Celer, eris, m."),
  array("Erras, meorum fur -auare- librorum",
        "Tu te trompes, voleur -avare- de mes livres.",
        "vocatif","auarus, i, m."),
  array("Ergo, -patrone- mi, bene vale Tironemque meum saluta nostris verbis.",
        "Adieu donc, mon cher -maître-, et salue pour moi mon cher Tiron.",
        "vocatif","patronus, i, m."),
  array("Sed heus -tu-, manum de tabula.","Hé, -toi-, lâche ta tablette.",
  "vocatif","te, tui"),
  array("Dic, -Naeui-, diem.","Fixe, -Naevius-, un jour.",
  "vocatif","Naeuius, ii, m."),
// accusatif        
  array("Videt ad ipsum fornicem Fabianum in turba -Verrem-.",
        "Il voit près de l'arc de Fabius, dans la foule, -Verrès-.",
        "accusatif","Verres, is, m."),
  array("appellat -hominem-.","Il appelle -l'homme-.",
        "accusatif","homo, inis, m."),
  array("Aliena quisquis recitat et petit famam,<br>" 
       ."       Non emere librum, sed -silentium- debet.",
       "Quiconque déclame les vers des autres et en réclame la renommée,"
       ."Ne doit pas acheter un livre, mais -le silence- (de son véritable auteur).",
       "accusatif","silentium, ii, n."),
  array("-uim- suscitat ira.","La colère réveille -la force-.",
  "accusatif","uis, -, f."),
  array("uehementer -me- haec res commouebat.","Cet événement -me- troublait profondément.",
  "accusatif","ego, mei, mf."),
  array("solem quis dicere -falsum- audeat ?","Qui oserait dire le soleil -trompeur- ?",
  "accusatif","falsus, a, um"),
  array("ille colit -terras-.","Il cultive -les terres-.",
  "accusatif","terra, ae, f."),
  array("heu fuge crudeles -terras-, fuge litus avarum.",
        "Hélas fuis -ces terres- cruelles, fuis ce rivage avare.",
        "accusatif","terra, ae, f."),
  array("-Audentes- fortuna iuuat.","La fortune aide -ceux qui osent-.",
  "accusatif","Audeo, es, ere, ausus sum"),
  array("-caelum- ipsum petimus stultitia.","Par sottise, nous cherchons à atteindre -le ciel- même.",
  "accusatif","caelum, i, n."),
  array("Plures -amicos- mensa quam mens concipit.",
        "La table fait -les amis- plus nombreux que l'intelligence.",
        "accusatif","amicus, i, m."),
  array("mali culices ranaeque palustres avertunt -somnos-.",
        "Les cousins importuns et les grenouilles des marais empêchent -les sommeils- (le sommeil).",
        "accusatif","somnus, i, m."),
  array("Timidus uocat se cautum, -parcum- sordidus",
        "Le lâche se dit prudent, et l'avare -économe-.",
        "accusatif","parcus, a, um"),
  array("gloriam -ingentem-, divitias honestas volebant.",
        "Ils voulaient que leur gloire fût -immense-, et leurs richesses honnêtes.",
        "accusatif","ingens, entis"),
  array("-proditionem- timebat.","Il craignait -une trahison-.",
        "accusatif","proditio, onis, f."),
  array("adhuc neminem cognovi -poetam- qui sibi non optumus videretur.",
        "Je n'ai encore connu aucun -poète- qui ne se prît pour le meilleur.",
        "accusatif","poeta, ae, m."),
  array("Accepi ab Aristocrito tris -epistulas-, quas ego lacrimis prope delevi.",
        "J'ai reçu par Aristocritus trois -lettres-, que j'ai presque effacé de mes larmes.",
        "accusatif","epistula, ae, f."),
  array("sunt quorum ingenium nova tantum -crustula- promit.",
        "Il est des gens dont le talent se borne à imaginer de nouvelles -pâtisseries-.",
        "accusatif","crustulum, i, n."),
  array("Pan primum -calamos- cera coniungere pluris instituit.",
        "Pan, le premier, commença à joindre plusieurs -roseaux- avec de la cire.",
        "accusatif","calamus, i, m."),
// génitif        
  array("-amici- officium neglexisti neque mihi consuluisti.",
        "Tu as négligé ton devoir -d'ami-, et tu n'as pas pensé à moi.",
        "génitif","amicus, i, m."),
  array("Oderunt peccare boni, -uirtutis- amore.",
        "Les bons ont horreur de mal agir, par amour de la -vertu-.",
        "génitif","uirtus, utis, f."),
  array("totus ordo -paucorum- improbitate et audacia premitur.",
        "Tout l'ordre de l'État est menacé par la malhonnêté et l'audace -de quelques uns-.",
        "génitif","pauci, ae, a"),
  array("est proprium -stultitiae- aliorum vitia cernere, oblivisci suorum.",
        "C'est le propre -de la bêtise- de remarquer les défauts des autres, et d'oublier les siens.",
        "génitif","stultitia, ae, f."),
  array("litora -patriae- lacrimans portusque relinquo et campos ubi Troia fuit.",
        "Je quitte en pleurant les rivages -de ma patrie-, et les plaines où fut Troie.",
        "génitif","patria, ae, f."),
  array("sub nomine -pacis- bellum latet","La guerre se cache sous le nom -de la paix-.",
  "génitif","pax, pacis, f."),
  array("-laudis- avidi, pecuniae liberales erant.",
        "Ils étaient avides -de louange-, et généreux de leur fortune.",
        "génitif","laus, laudis, f."),
  array("uidete -hominis- amentiam.","Constatez la folie -de cet homme-.",
        "génitif","homo, minis, m."),
  array("uenit ipse in aedem -Castoris-.","Il vient lui-même dans le temple -de Castor-.",
        "génitif","Castor, oris, m."),
  array("de -amicorum- cognatorumque sententia Romam confugit.",
        "Sur le conseil -de ses amis- et de ses parents, il fuit Rome.",
        "génitif","amicus, i, m."),
  array("Quis umquam templum illud aspexit quin -auaritiae- tuae, quin iniuriae, "
       ."quin audaciae testis esset ?",
        "Qui a jamais vu ce temple sans être témoin -de ta convoitise-, de ton injustice, "
        ."de ton impudence ?",
        "génitif","auaritia, ae, f."),
  array("-Crassi- erat filia.","C'était la fille -de Crassus-.",
        "génitif","Crassus, i, m."),
  array("Pater -deorum- risit atque illis dedit parvum tigillum.",
        "Le père -des dieux- rit, et leur donna une petite poutre.",
        "génitif","deus, i, m."),
  array("Deinde contemnens suos se immiscuit -pauonum- formoso gregi.",
        "Puis méprisant les siens, il se mêla au troupeau gracieux -des paons-.",
        "génitif","pauo, onis, m."),
  array("Hi cum cepissent cervum uasti -corporis-, sic est locutus, partibus factis, leo :",
        "Après qu'ils eurent pris un cerf au vaste -corps-, les parts ayant été faites, "
        ."le lion parla ainsi :",
        "génitif","corpus, oris, n."),
  array("Vicini -furis- celebres uidit nuptias Aesopus.",
        "Ésope vit les noces fastueuses d'un voisin -voleur-.",
        "génitif","fur, furis, m."),
  array("-crurum- nimiam tenuitatem vituperat","Il blâme la trop grande maigreur -de ses pattes-.",
        "génitif","crus, cruris, n."),
  array("pallida Mors aequo pulsat pede -pauperum- tabernas regumque turris.",
        "La pâle Mort heurte du même pied aux cabanes -des pauvres- et aux châteaux des rois.",
        "génitif","pauper, eris"),
  array("Si hostium fuit ille sanguis, summa militum pietas : nefarium scelus, si -ciuium-.",
        "Si ce sang a été celui des ennemis, grand a été le patriotisme des soldats. Mais ce fut "
        ."un crime abominable, s'il a été celui -des citoyens-.",
        "génitif","ciuis, is, m."),
// datif        
  array("o vita misero longa, -felici- brevis !",
        "Oh vie, longue pour le malheureux, brève -pour l'homme heureux- !",
        "datif","felix, icis"),
  array("Quae locutus est Furnius noster de animo tuo in rem publicam, ea gratissima fuerunt -senatui-.",
        "L'intervention de notre cher Furnius au sujet de ton attachement à la république a été très "
        ."agréable -au sénat-.",
        "datif","senatus, us, m."),
  array("Renuntio, inquit, -tibi-, te hodiernis comitiis esse absolutum.",
        "Je -t'-annonce, dit~il, que tu es absous par les comices d'aujourd'hui.",
        "datif","te, tui"),
  array("Si memini, fuerant -tibi- quattuor, Aelia, dentes.",
        "Si je me souviens bien, Aelia, tu avais quatre dents (quatre dents étaient -à toi-).",
        "datif","te, tui"),
  array("-cineri- gloria sera uenit.",
        "La gloire vient trop tard -pour la cendre- (= pour ceux qui sont morts).",
        "datif","cinis, cineris, m."),
  array("Urbanus tibi, Caecili, uideris.<br>  Non es, crede -mihi-.",
        "Tu te crois spirituel, Caecilius.<br> Tu ne l'es pas, fais~-moi- confiance.",
        "datif","ego, mei"),
  array("Caesar -Trebonio- per nuntium epistulam misit.",
        "César envoya une lettre -à Trébonius- par un messager.",
        "datif","Trebonius, ii, m."),
  array("At pol ego te adiuuo nam -bonis- quod bene fit haud perit.",
        "Mais, ma parole, je vais t'aider : le bien qu'on fait -aux hommes bons- n'est pas perdu.",
        "datif","boni, orum, m."),
  array("-pedibus- timor addidit alas.","La peur ajouta des ailes -à ses pieds-.",
        "datif","pes, pedis, m."),
  array("nil -mortalibus- ardui est.","-Pour les (aux yeux des) mortels-, il n'est rien de pénible.",
        "datif","mortalis, e"),
  array("Stat sua -cuique- dies.","Le jour (fatal) est fixé -pour chacun-.",
        "datif","quisque, quaeque, quidque"),
  array("Ingratus unus omnibus -miseris- nocet.","Un seul ingrat nuit à tous -les malheureux-.",
        "datif","miser, era, erum"),
  array("docto -homini- et erudito, uivere est cogitare.","-Pour l'homme- instruit et savant, "
       ."vivre, c'est méditer.",
       "datif","homo, minis, m."),
  array("Stultum est imperare ceteris qui nescit -sibi-.",
        "Il est insensé qu'on commande aux autres si l'on ne sait commander -à soi~même-.",
        "datif","se, sui"),
  array("proditores etiam -iis- quos anteponunt inuisi sunt.",
        "Les traîtres sont odieux même -à ceux- à qui ils donnent la préférence.",
        "datif","is, ea, id"),
  array("ille uelut -pelago- rupes immota resistit.",
        "Il résiste, comme le rocher immobile résiste -à la mer-.",
        "datif","pelagus, i, n."),
  array("solue metus ; feret haec aliquam -tibi- fama salutem.",
        "Dissipe tes craintes ; ta renommée -t'-apportera quelque aide.",
        "datif","te, tui"),
  array("-pueris- olim dant crustula blandi doctores, elementa velint ut discere prima.",
        "Les maîtres indulgents donnent parfois des friandises -aux enfants-, "
        ."pour qu'ils acceptent d'apprendre les premiers éléments.",
        "datif","puer, eri, m."),
  // double datif
  array("Mihi tu, tui, tua omnia maximae -curae- sunt.",
        "Toi, les tiens, tout ce qui te touche, sont pour moi -l'objet de la plus grande sollicitude-.",
        "datif","cura, ae, f.")
);
?>
