<?php
$lex = array(
   array("adulescens","adulescent","ciuis","m","entis, m. : jeune homme"),
   array("aedes","aed","ciuis","f","is, f. : temple ; au pl. : maison"),
   array("amnis","amn","ciuis","m","is, m. : rivière, fleuve"),
   array("apis","ap","ciuis","f","is, f. : abeille"),
   array("ars","art","ciuis","f","artis, f. : habileté, métier, connaissance technique, art"),
   array("auis","au","ciuis","m","is, m. : oiseau"),
   array("auris","aur","ciuis","f","is, f. : oreille"),
   array("caedes","caed","ciuis","f","is, f. : meurtre, massacre"),
   array("ciuis","ciu","ciuis","m","is, m. : citoyen"),
   array("classis","class","ciuis","f","is, f. : classe, flotte"),
   array("collis","coll","ciuis","m","is, m. : colline"),
   array("dens","dent","ciuis","f","dentis, f. : dent"),
   array("finis","fin","ciuis","f","is, f. : limite, fin ; pl., frontière, territoire"),
   array("fons","font","ciuis","m","fontis, m. : la source, la fontaine"),
   array("gens","gent","ciuis","f","gentis, f. : tribu, famille, peuple"),
   array("hostis","host","ciuis","m","is, m. : ennemi"),
   //array("ignis","ign","ciuis","m","is, m. : feu"),
   array("infans","infant","ciuis","m","antis, m. : bébé"),
   array("moles","mol","ciuis","f","is, f. : la masse"),
   array("nauis","nau","ciuis","f","is, f. : navire"),
   array("nox","noct","ciuis","f","noctis, f. : nuit"),
   array("nubes","nub","ciuis","f","is, f. : le nuage, la nue, la nuée"),
   array("orbis","orb","ciuis","m","is, m. : cercle globe. - terrarum : le monde"),
   array("parens","parent","ciuis","m","entis, m. : parent"),
   array("pars","part","ciuis","f","partis, f. : partie, côté"),
   array("piscis","pisc","ciuis","m","is, m. : poisson"),
   array("pons","pont","ciuis","m","pontis, m. : le pont"),
   array("ratis","rat","ciuis","f","is, f. : le radeau, le navire"),
   array("testis","test","ciuis","m","is, m. : témoin"),
   array("turris","turr","ciuis","f","is, f. : tour"),
   array("uestis","uest","ciuis","f","is, f. : vêtement"),
   array("urbs","urb","ciuis","f","urbis, f. : ville"),
   );
?>
