<?php
$lex = array(
  array("aequor","aequor","corpus","n","oris, n. : la plaine, la mer"),
  array("aes","aer","corpus","n","aeris, n. : le bronze ; monnaie de cuivre = as"),
  array("agmen","agmin","corpus","n","inis, n. : l'armée en marche, la colonne de marche"),
  array("caput","capit","corpus","n","itis, n. : tête, extrémité, vie, capitale"),
  array("carmen","carmin","corpus","n","minis, n. : poème, incantation"),
  array("certamen","certamin","corpus","n","inis, n. : combat, lutte, conflit"),
  array("corpus","corpor","corpus","n","oris, n. : corps"),
  array("crimen","crimin","corpus","n","inis, n. : accusation, grief, faute, crime"),
  array("decus","decor","corpus","n","oris, n. : gloire, honneur"),
  array("discrimen","discrimin","corpus","n","inis, n. : différence, distinction, position critique"),
  array("facinus","facinor","corpus","n","oris, n. :  action, crime"),
  array("flumen","flumin","corpus","n","inis, n. : cours d'eau, fleuve, rivière"),
  array("foramen","foramin","corpus","n","inis, n. : le trou, l'ouverture"),
  array("frigus","frigor","corpus","n","oris, n. : le froid, la froidure"),
  array("fulmen","fulmin","corpus","n","inis, n. : foudre"),
  array("funus","funer","corpus","n","eris, n. : funérailles, ensevelissement ; mort, ruine"),
  array("genus","gener","corpus","n","eris, n. : race, origine, espèce"),
  array("iter","itiner","corpus","n","itineris, n. : chemin"),
  array("ius","iur","corpus","n","iuris, n. : 1. la loi, le serment, le droit 2. jus, sauce"),
  array("latus","later","corpus","n","eris, n. : le côté"),
  array("limen","limin","corpus","n","inis, n. : seuil, entrée"),
  array("litus","litor","corpus","n","oris, n. : rivage"),
  array("lumen","lumin","corpus","n","inis, n. : lumière, flambeau, jour, pl. yeux"),
  array("munus","muner","corpus","n","eris, n. : office, fonction, service rendu, don, spectacle"),
  array("nemus","nemor","corpus","n","oris, n. : la forêt, le bois"),
  array("nomen","nomin","corpus","n","inis, n. : nom"),
  array("numen","numin","corpus","n","inis, n. volonté ; volonté des dieux, dieu"),
  array("onus","oner","corpus","n","eris, n. : fardeau"),
  array("opus","oper","corpus","n","operis, n. : le travail (opus est mihi = j'ai besoin)"),
  array("os","oss","corpus","n","ossis, n. : os"),
  array("pectus","pector","corpus","n","oris, n. : la poitrine, le coeur, l'intelligence"),
  array("pecus","pecor","corpus","n","oris, n. : le bétail"),
  array("plus","plur","corpus","n","pluris, n. : plus, plus cher"),
  array("pondus","ponder","corpus","n","eris, n. : poids"),
  array("robur","robor","corpus","n","oris, n. : le rouvre, le chêne, la dureté, la solidité"),
  array("scelus","sceler","corpus","n","eris, n. : crime"),
  array("semen","semin","corpus","n","inis, n. : la graine, la semence"),
  array("tempus","tempor","corpus","n","oris, n. : moment, instant, temps"),
  array("uer","uer","corpus","n","eris, n. : le printemps"),
  array("uulnus","uulner","corpus","n","eris, n. : blessure")
  );
?>
