<?php
$lex = array(
   array("aditus","adit","manus","m","us, m. : accès"),
   array("aduentus","aduent","manus","m","us, m. : l'arrivée, la venue"),
   array("aestus","aest","manus","m","us, m. : chaleur, bouillonnement, vagues, marée"),
   array("affectus","affect","manus","m","us, m. : la disposition de l'âme, le sentiment"),
   array("casus","cas","manus","m","us, m. : le hasard, le malheur, la chute"),
   array("conspectus","conspect","manus","m","us, m. : vue, regard"),
   array("consulatus","consulat","manus","m","us, m. : consulat"),
   array("cornu","corn","manus","n","us, n. : corne, aile d'une ligne de bataille. "),
   array("cultus","cult","manus","m","us, m. : culture, soin, éducation, culte, respect"),
   array("currus","curr","manus","m","us, m. : le char"),
   array("cursus","curs","manus","m","us, m. : la course, le parcours, le trajet"),
   //array("domus","dom","manus","f","us, f. : la maison"),
   array("equitatus","equitat","manus","m","us, m. : cavalerie"),
   array("exercitus","exercit","manus","m","us, m. : l'armée"),
   array("exitus","exit","manus","m","us, m. : sortie, résultat, mort, fin"),
   array("fructus","fruct","manus","m","us, m. : droit sur qqch, fruit, récompense, résultat"),
   array("genu","ge","manus","n",": le genou"),
   array("gradus","grad","manus","m","us, m. : pas, degré"),
   array("habitus","habit","manus","m","us, m. : manière d'être, apparence"),
   array("ictus","ict","manus","m","us, m. : le coup, le choc"),
   array("impetus","impet","manus","m","us, m. : mouvement en avant, élan, assaut"),
   array("magistratus","magistrat","manus","m","us, m. : charge, fonction publique"),
   array("manus","man","manus","f","us, f. : main, petite troupe"),
   array("metus","met","manus","m","us, m. : peur, crainte"),
   array("motus","mot","manus","m","us, m. : mouvement, trouble, révolte, émotion, excitation"),
   array("paratus","parat","manus","m","us, m. : la préparation, l'apprêt, le préparatif"),
   array("passus","pass","manus","m","us, m. : pas (1, 479 m.)"),
   array("porticus","portic","manus","f","us, f. : le portique"),
   array("portus","port","manus","m","us, m. : port"),
   array("senatus","senat","manus","m","us, m. : sénat"),
   array("sensus","sens","manus","m","us, m. : le sens, les sentiments"),
   array("sinus","sin","manus","m","us, m. : le sein, la courbure, le golfe, l'anse"),
   array("spiritus","spirit","manus","m","us, m. : air, souffle, vie, orgueil"),
   array("uersus","uers","manus","m","us, m., : sillon, ligne, vers"),
   array("usus","us","manus","m","us, m. : l'usage, l'utilité"),
   array("uultus","uult","manus","m","us, m. : le regard, le visage")
   );
?>
