<?php
$lex = array(
  array("aer","aer","miles","m","aeris, m. : air"),
  array("aetas","aetat","miles","f","atis, f. : temps de la vie, vie, âge, époque"),
  array("altitudo","altitudin","miles","f","dinis, f. : altitude, hauteur"),
  array("amor","amor","miles","m","oris, m. : amour"),
  array("arbor","arbor","miles","f","oris, f. : l'arbre"),
  array("ardor","ardor","miles","m","oris, m. : le feu, l'embrasement, l'ardeur, la passion"),
  array("arx","arc","miles","f","arcis, f. : citadelle"),
  array("auctor","auctor","miles","m","oris, m. : source, modèle, auteur"),
  array("auctoritas","auctoritat","miles","f","atis, f. : avis, prestige, autorité, décision"),
  array("bos","bou","miles","m","bouis, m. : boeuf"),
  array("canis","can","miles","m","is, m. : chien"),
  array("centurio","centurion","miles","f","ionis, f. : le centurion"),
  array("ceruix","ceruic","miles","f","icis, f. (svt au pl.)  : nuque, encolure"),
  array("ciuitas","ciuitat","miles","f","atis, f. : cité, état"),
  array("clamor","clamor","miles","m","oris, m. : clameur, cri"),
  array("cohors","cohort","miles","f","ortis, f. : cohorte"),
  array("color","color","miles","m","oris, m. : couleur, teint du visage, éclat (du style)"),
  array("comes","comit","miles","m","itis, m. : compagnon"),
  array("condicio","condicion","miles","f","onis, f. : condition"),
  array("coniux","coniug","miles","f","iugis, m. ou f. : épouse, époux"),
  array("consuetudo","consuetudin","miles","f","dinis, f. : habitude, coutume"),
  array("consul","consul","miles","m","is, m. : consul"),
  array("crassitudo","crassitudin","miles","f","dinis, f. : épaisseur, grosseur"),
  array("cupiditas","cupiditat","miles","f","atis, f. : désir"),
  array("custos","custod","miles","m","odis, m. : gardien"),
  array("difficultas","difficultat","miles","f","atis, f. : la difficulté"),
  array("dignitas","dignitat","miles","f","atis, f. : dignité, considération, prestige"),
  array("dolor","dolor","miles","m","oris, m. : la douleur"),
  array("dux","duc","miles","m","ducis, m. : le chef, le guide"),
  array("eques","equit","miles","m","itis, m. : chevalier, cavalier"),
  array("error","error","miles","m","oris, m. : écart, détour, circuit, erreur"),
  array("fax","fac","miles","f","facis, f. : torche"),
  array("felicitas","felicitat","miles","f","atis, f. : bonheur"),
  //array("fides","fid","miles","f","ium, f. : lyre"),
  array("frater","fratr","miles","m","tris, m. : frère"),
  array("fraus","fraud","miles","f","fraudis, f. : mauvaise foi, tromperie"),
  array("frons","frond","miles","f","frondis, f. : feuillage"),
  array("gladiator","gladiator","miles","m","oris, m. : gladiateur"),
  array("grauitas","grauitat","miles","f","atis, f. : pesanteur, sévérité, dignité, maladie"),
  array("grex","greg","miles","m","gregis, m. : troupeau"),
  array("hiems","hiem","miles","m","hiemis, m. : l'hiver"),
  array("homo","homin","miles","m","minis, m. : homme, humain"),
  array("honor","honor","miles","m","oris, m. : honneur, hommage, magistrature"),
  array("honos","honor","miles","m","oris, m. : honneur, hommage, magistrature"),
  array("humor","humor","miles","m","oris, m. : eau, liquide"),
  array("imago","imagin","miles","f","inis, f. : imitation, image"),
  array("imber","imbr","miles","m","bris, m. : la pluie"),
  array("imperator","imperator","miles","m","oris, m. : général"),
  array("intentio","intention","miles","f","onis, f. : application, effort, volonté"),
  array("iudex","iudic","miles","m","icis, m. : juge"),
  array("iuuenis","iuuen","miles","m","is, m. : jeune homme"),
  array("iuuentus","iuuentut","miles","f","tutis, f. : jeunesse"),
  array("lapis","lapid","miles","m","idis, m. : pierre"),
  array("latitudo","latitudin","miles","f","inis, f. : la largeur"),
  array("laus","laud","miles","f","laudis, f. : louange, gloire, honneur"),
  array("legio","legion","miles","f","onis, f. : légion"),
  array("lex","leg","miles","f","legis, f. : loi, condition(s) d'un traité"),
  array("libertas","libertat","miles","f","atis, f. : la  liberté"),
  array("libido","libidin","miles","f","dinis, f. : désir, envie, débauche"),
  array("lux","luc","miles","f","lucis, f. : lumière, jour"),
  array("magnitudo","magnitudin","miles","f","dinis, f. : grande taille"),
  array("maiores","maior","miles","m","um, m. : les ancêtres"),
  array("mater","matr","miles","f","tris, f. : mère"),
  array("mens","ment","miles","f","entis, f. : esprit"),
  array("miles","milit","miles","m","itis, m. : soldat"),
  array("mons","mont","miles","m","montis, m. : montagne"),
  array("mors","mort","miles","f","mortis, f. : mort"),
  array("mos","mor","miles","m","moris, m. : sing. : coutume, manière ; pl. : moeurs"),
  array("multitudo","multitudin","miles","f","dinis, f. : foule, grand nombre"),
  array("munitio","munition","miles","f","ionis, f. : terrassement, fortification, rempart"),
  array("natio","nation","miles","f","onis, f. : nation, nationalité"),
  array("necessitas","necessitat","miles","f","atis, f. : nécessité"),
  array("opinio","opinion","miles","f","onis, f : opinion, idée préconçue, préjugé, illusion"),
  array("ops","op","miles","f","opis, f. : sing., pouvoir, aide ; pl., richesses"),
  array("oratio","oration","miles","f","onis, f. : le langage, la parole, l'exposé, le discours"),
  array("ordo","ordin","miles","m","inis, m. : le rang,  l'ordre, la file (de soldats), la centurie ; ordine, adv. : régulièrement"),
  array("paries","pariet","miles","m","etis, m. : mur"),
  array("pater","patr","miles","m","tris, m. : père, magistrat "),
  array("paupertas","paupertat","miles","f","atis, f. : pauvreté"),
  array("pax","pac","miles","f","pacis, f. : paix"),
  array("pedes","pedit","miles","m","itis, m. : le fantassin, le piéton"),
  array("pes","ped","miles","m","pedis, m. : pied"),
  array("pietas","pietat","miles","f","atis, f. : le respect, le patriotisme, l'affection"),
  array("plebs","pleb","miles","f","plebis, f. : la plèbe"),
  array("potestas","potestat","miles","f","atis, f. : 1.  la puissance, le pouvoir 2.  le pouvoir d'un magistrat  3.  la faculté, l'occasion de faire qqch. "),
  array("praetor","praetor","miles","m","oris, m. : préteur"),
  array("pudor","pudor","miles","m","oris, m. : honte"),
  array("puluis","puluer","miles","m","eris, m. : poussière"),
  array("quies","quiet","miles","f","etis, f. : tranquilité"),
  array("ratio","ration","miles","f","onis, f. : la raison, le raisonnement, le compte"),
  array("regio","region","miles","f","onis, f. : la région, l'arrondissement"),
  array("rex","reg","miles","m","regis, m. : le roi"),
  array("sanguis","sanguin","miles","m","inis, m. : le sang, la vigueur"),
  array("sedes","sed","miles","f","is, f. : siège, place"),
  array("senectus","senectut","miles","f","utis, f. : vieillesse"),
  array("senex","sen","miles","m","senis, m. : vieillard"),
  array("sermo","sermon","miles","m","onis, m. : conversation, le discours, langue"),
  array("sol","sol","miles","m","solis, m. : soleil"),
  array("soror","soror","miles","f","oris, f. : soeur"),
  array("tellus","tellur","miles","f","uris, f. : terre, sol, terrain, pays"),
  array("tempestas","tempestat","miles","f","atis, f. : temps, mauvais temps"),
  array("terror","terror","miles","m","oris, m. : terreur, effroi, épouvante"),
  array("timor","timor","miles","m","oris, m. : peur"),
  array("uates","uat","miles","m","le devin, le poète"),
  array("uictor","uictor","miles","m","oris, m. : vainqueur"),
  array("uirgo","uirgin","miles","f","ginis, f. : vierge, jeune fille non mariée"),
  array("uirtus","uirtut","miles","f","utis, f. : courage, honnêteté"),
  array("umor","umor","miles","m","oris, m. : eau, liquide"),
  array("uoluntas","uoluntat","miles","f","atis, f. : volonté"),
  array("uoluptas","uoluptat","miles","f","atis, f. : volupté"),
  array("uox","uoc","miles","f","uocis, f. : voix, accent, son, parole, le mot"),
  array("utilitas","utilitat","miles","f","atis, f. : utilité"),
  array("uxor","uxor","miles","f","oris, f. : épouse, femme")
  )
?>
