<?php
$titre = 'Les noms à savoir en fin de cinquième';
$bini=array(
    array("acies","aciei","res","f. : ligne de bataille;  regard"),
    array("adulescens","adulescentis","ciuis","m. : jeune homme. Première lettre : a"),
    array("aetas","aetatis","miles","f. : temps de la vie, âge, époque"),
    array("ager","agri","ager","m. : terre, territoire, champ. Première lettre : a"),
    array("agmen","agminis","corpus","n. : armée en marche, colonne de marche"),
    array("animus","animi","amicus","m. : coeur, sympathie, courage, esprit"),
    array("annus","anni","amicus","m. : année"),
    array("aqua","aquae","uita","f. : eau"),
    array("ara","arae","uita","f. : autel"),
    array("arma","armorum","templum","n. pl. : armes"),
    array("augur","auguris","miles","m. : augure"),
    array("auspicium","auspicii","templum","n. : auspice"),
    array("auis","auis","ciuis","m. : oiseau"),
    array("auus","aui","amicus","m. : ancêtre, aïeul, grand-père"),
    array("bellum","belli","templum","n. : guerre"),
    array("caedes","caedis","ciuis","f. : meurtre, massacre"),
    array("caelum","caeli","templum","n. : ciel"),
    array("campus","campi","amicus","m. : plaine, champ. Première lettre : c"),
    array("castra","castrorum","templum","n. pl. : camp militaire"),
    array("centurio","centurionis","miles","m. : centurion"),
    array("ciuis","ciuis","ciuis","m. : citoyen"),
    array("ciuitas","ciuitatis","miles","f. : cité, état"),
    array("clades","cladis","ciuis","f. : blessure, perte, dommage, désastre militaire, grave défaite"),
    array("coniux","coniugis","miles","m. ou f. : époux, épouse, conjoint"),
    array("consilium","consilii","templum","n. : délibération, assemblée, projet, plan"),
    array("consul","consulis","miles","m. : consul"),
    array("corpus","corporis","corpus","n. : corps"),
    array("dea","deae","uita","f. : déesse"),
    array("decus","decoris","corpus","n. : gloire, honneur. Première lettre : d"),
    array("deus","dei","amicus","m. : dieu"),
    array("dies","diei","res","m. et f. : jour"),
    array("domus","domus","manus","f. : maison"),
    array("dux","ducis","miles","m. : chef, guide"),
    array("equus","equi","amicus","m. : cheval"),
    array("fama","famae","uita","f. : nouvelle, rumeur, réputation"),
    array("familia","familiae","uita","f. : famille, maisonnée"),
    array("fides","fidei","res","f. : confiance, loyauté"),
    array("filia","filiae","uita","f. : fille"),
    array("filius","filii","amicus","m. : fils"),
    array("fines","finium","ciuis","f. p. : frontières, territoire, pays"),
    array("flumen","fluminis","corpus","n. : cours d'eau, fleuve, rivière"),
    array("forum","fori","templum","n. : marché, forum"),
    array("frater","fratris","miles","m. : frère"),
    array("fuga","fugae","uita","f. : fuite"),
    array("gens","gentis","ciuis","f. : tribu, famille, peuple"),
    array("gloria","gloriae","uita","f. : gloire, renom"),
    array("hiems","hiemis","miles","m. : hiver"),
    array("homo","hominis","miles","m. : homme, humain"),
    array("hortus","horti","amicus","m. : jardin"),
    array("hostis","hostis","ciuis","m. : ennemi"),
    array("ignis","ignis","ciuis","m. : feu"),
    array("imago","imaginis","miles","f. : imitation, image"),
    array("imperator","imperatoris","miles","m. : général"),
    array("ingenium","ingenii","templum","n. : qualités innées, caractère, talent, intelligence"),
    array("iter","itineris","corpus","n. : chemin"),
    array("iuuenis","iuuenis","miles","m. : jeune homme. Première lettre : i"),
    array("laus","laudis","miles","f. : louange, gloire, honneur"),
    array("legatus","legati","amicus","m. : légat, envoyé"),
    array("legio","legionis","miles","f. : légion"),
    array("lex","legis","miles","f. : loi, condition(s) d'un traité"),
    array("liberi","liberorum","puer","m. pl. : enfants (fils et filles)"),
    array("locus","loci","amicus","m. : lieu, endroit; place, rang; situation"),
    array("mare","maris","mare","n. : mer"),
    array("mater","matris","miles","f. : mère"),
    array("miles","militis","miles","m. : soldat"),
    array("moenia","moenium","mare","n. : murs, murailles"),
    array("mors","mortis","miles","f. : mort"),
    array("mulier","mulieris","miles","f. : femme"),
    array("nauis","nauis","ciuis","f. : navire"),
    array("nomen","nominis","corpus","n. : nom, titre"),
    array("nox","noctis","ciuis","f. : nuit"),
    array("numen","numinis","corpus","n. volonté des dieux, puissance divine; dieu, divinité"),
    array("oppidum","oppidi","templum","n. : oppidum"),
    array("pars","partis","ciuis","f. : partie, côté"),
    array("pater","patris","miles","m. : père, magistrat, au pl., avec maj. : les sénateurs"),
    array("patria","patriae","uita","f. : patrie"),
    array("pax","pacis","miles","f. : paix"),
    array("penates","penatium","ciuis","m. pl. : pénates"),
    array("pes","pedis","miles","m. : pied"),
    array("piscis","piscis","ciuis","m. : poisson"),
    array("populus","populi","amicus","m. : peuple"),
    array("praeda","praedae","uita","f. : butin, dépouilles, proie"),
    array("preces","precum","miles","f. pl. : prières"),
    array("proelium","proelii","templum","n. : combat"),
    array("puella","puellae","uita","f. : fille, jeune fille"),
    array("puer","pueri","puer","m. : enfant, jeune esclave"),
    array("pugna","pugnae","uita","f. : bataille, combat, pugilat"),
    array("respublica","reipublicae","uita","f. : état, politique, république"),
    array("rex","regis","miles","m. : roi"),
    array("sacerdos","sacerdotis","miles","m. : prêtre"),
    array("senatus","senatus","manus","m. : sénat"),
    array("senex","senis","miles","m. : vieillard"),
    array("seruus","serui","amicus","m. : esclave"),
    array("signum","signi","templum","n. : signe, enseigne, oeuvre d'art"),
    array("silua","siluae","uita","f. : forêt"),
    array("socius","socii","amicu","associé, allié"),
    array("soror","sororis","miles","f. : soeur"),
    array("spatium","spatii","templum","n. : distance, espace (lieu ou temps)"),
    array("templum","templi","templum","n. : temple"),
    array("tempus","temporis","corpus","n. : moment, instant, temps, occasion"),
    array("terra","terrae","uita","f. : terre"),
    array("unda","undae","uita","f. : onde, eau, flot"),
    array("urbs","urbis","ciuis","f. : ville"),
    array("uxor","uxoris","miles","f. : épouse, femme"),
    array("uer","ueris","corpus","n. : printemps"),
    array("uia","uiae","uita","f. : route, chemin, voyage"),
    array("uictoria","uictoriae","uita","f. : victoire"),
    array("uir","uiri","pueri","m. : homme ( par opp. à mulier, femme ), mari."),
    array("uirtus","uirtutis","miles","f. : courage, honnêteté"),
    array("uita","uitae","uita","f. : vie"),
    array("uitium","uitii","templum","n. : vice, défaut"),
);
?>
