<?php
$titre = 'Les noms à savoir en fin de quatrième';
$bini=array(
    array("acies","aciei","res","f. : ligne de bataille;  regard"),
    array("adulescens","adulescentis","ciuis","m. : jeune homme"),
    array("aetas","aetatis","miles","f. : temps de la vie, âge, époque"),
    array("ager","agri","ager","m. : terre, territoire, champ"),
    array("agmen","agminis","corpus","n. : armée en marche, colonne de marche"),
    array("animus","animi","amicus","m. : coeur, sympathie, courage, esprit"),
    array("annus","anni","amicus","m. : année"),
    array("aqua","aquae","uita","f. : eau"),
    array("ara","arae","uita","f. : autel"),
    array("arma","armorum","templum","n. pl. : armes"),
    array("augur","auguris","miles","m. : augure"),
    array("auspicium","auspicii","templum","n. : auspice"),
    array("auis","auis","ciuis","m. : oiseau"),
    array("auus","aui","amicus","m. : ancêtre, aïeul, grand-père"),
    array("bellum","belli","templum","n. : guerre"),
    array("caedes","caedis","ciuis","f. : meurtre, massacre"),
    array("caelum","caeli","templum","n. : ciel"),
    array("campus","campi","amicus","m. : plaine, champ"),
    array("castra","castrorum","templum","n. pl. : camp militaire"),
    array("centurio","centurionis","miles","m. : centurion"),
    array("ciuis","ciuis","ciuis","m. : citoyen"),
    array("ciuitas","ciuitatis","miles","f. : cité, état"),
    array("clades","cladis","ciuis","f. : blessure, perte, dommage, désastre militaire, grave défaite"),
    array("coniux","coniugis","miles","m. ou f. : époux, épouse, conjoint"),
    array("consilium","consilii","templum","n. : délibération, assemblée, projet, plan"),
    array("consul","consulis","miles","m. : consul"),
    array("corpus","corporis","corpus","n. : corps"),
    array("dea","deae","uita","f. : déesse"),
    array("decus","decoris","corpus","n. : gloire, honneur"),
    array("deus","dei","amicus","m. : dieu"),
    array("dies","diei","res","m. et f. : jour"),
    array("domus","domus","manus","f. : maison"),
    array("dux","ducis","miles","m. : chef, guide"),
    array("equus","equi","amicus","m. : cheval"),
    array("fama","famae","uita","f. : nouvelle, rumeur, réputation"),
    array("familia","familiae","uita","f. : famille, maisonnée"),
    array("fides","fidei","res","f. : confiance, loyauté"),
    array("filia","filiae","uita","f. : fille"),
    array("filius","filii","amicus","m. : fils"),
    array("fines","finium","ciuis","f. p. : frontières, territoire, pays"),
    array("flumen","fluminis","corpus","n. : cours d'eau, fleuve, rivière"),
    array("forum","fori","templum","n. : marché, forum"),
    array("frater","fratris","miles","m. : frère"),
    array("fuga","fugae","uita","f. : fuite"),
    array("gens","gentis","ciuis","f. : tribu, famille, peuple"),
    array("gloria","gloriae","uita","f. : gloire, renom"),
    array("hiems","hiemis","miles","m. : hiver"),
    array("homo","hominis","miles","m. : homme, humain"),
    array("hortus","horti","amicus","m. : jardin"),
    array("hostis","hostis","ciuis","m. : ennemi"),
    array("ignis","ignis","ciuis","m. : feu"),
    array("imago","imaginis","miles","f. : imitation, image"),
    array("imperator","imperatoris","miles","m. : général"),
    array("ingenium","ingenii","templum","n. : qualités innées, caractère, talent, intelligence"),
    array("iter","itineris","corpus","n. : chemin"),
    array("iuuenis","iuuenis","miles","m. : jeune homme. Première lettre : i"),
    array("laus","laudis","miles","f. : louange, gloire, honneur"),
    array("legatus","legati","amicus","m. : légat, envoyé"),
    array("legio","legionis","miles","f. : légion"),
    array("lex","legis","miles","f. : loi, condition(s) d'un traité"),
    array("liberi","liberorum","puer","m. pl. : enfants (fils et filles)"),
    array("locus","loci","amicus","m. : lieu, endroit; place, rang; situation"),
    array("mare","maris","mare","n. : mer"),
    array("mater","matris","miles","f. : mère"),
    array("miles","militis","miles","m. : soldat"),
    array("moenia","moenium","mare","n. : murs, murailles"),
    array("mors","mortis","miles","f. : mort"),
    array("mulier","mulieris","miles","f. : femme"),
    array("nauis","nauis","ciuis","f. : navire"),
    array("nomen","nominis","corpus","n. : nom, titre"),
    array("nox","noctis","ciuis","f. : nuit"),
    array("numen","numinis","corpus","n. volonté des dieux, puissance divine; dieu, divinité"),
    array("oppidum","oppidi","templum","n. : oppidum"),
    array("pars","partis","ciuis","f. : partie, côté"),
    array("pater","patris","miles","m. : père, magistrat, au pl., avec maj. : les sénateurs"),
    array("patria","patriae","uita","f. : patrie"),
    array("pax","pacis","miles","f. : paix"),
    array("penates","penatium","ciuis","m. pl. : pénates"),
    array("pes","pedis","miles","m. : pied"),
    array("piscis","piscis","ciuis","m. : poisson"),
    array("populus","populi","amicus","m. : peuple"),
    array("praeda","praedae","uita","f. : butin, dépouilles, proie"),
    array("preces","precum","miles","f. pl. : prières"),
    array("proelium","proelii","templum","n. : combat"),
    array("puella","puellae","uita","f. : fille, jeune fille"),
    array("puer","pueri","puer","m. : enfant, jeune esclave"),
    array("pugna","pugnae","uita","f. : bataille, combat, pugilat"),
    array("respublica","reipublicae","uita","f. : état, politique, république"),
    array("rex","regis","miles","m. : roi"),
    array("sacerdos","sacerdotis","miles","m. : prêtre"),
    array("senatus","senatus","manus","m. : sénat"),
    array("senex","senis","miles","m. : vieillard"),
    array("seruus","serui","amicus","m. : esclave"),
    array("signum","signi","templum","n. : signe, enseigne, oeuvre d'art"),
    array("silua","siluae","uita","f. : forêt"),
    array("socius","socii","amicu","associé, allié"),
    array("soror","sororis","miles","f. : soeur"),
    array("spatium","spatii","templum","n. : distance, espace (lieu ou temps)"),
    array("templum","templi","templum","n. : temple"),
    array("tempus","temporis","corpus","n. : moment, instant, temps, occasion"),
    array("terra","terrae","uita","f. : terre"),
    array("unda","undae","uita","f. : onde, eau, flot"),
    array("urbs","urbis","ciuis","f. : ville"),
    array("uxor","uxoris","miles","f. : épouse, femme"),
    array("uer","ueris","corpus","n. : printemps"),
    array("uia","uiae","uita","f. : route, chemin, voyage"),
    array("uictoria","uictoriae","uita","f. : victoire"),
    array("uir","uiri","pueri","m. : homme ( par opp. à mulier, femme ), mari."),
    array("uirtus","uirtutis","miles","f. : courage, honnêteté"),
    array("uita","uitae","uita","f. : vie"),
    array("uitium","uitii","templum","n. : vice, défaut"),
    array("amicitia","amicitiae","uita","f. : amitié"),
    array("amicus","amici","amicus","m. : ami"),
    array("amor","amoris","miles","m. : amour"),
    array("arbor","arboris","miles","f. : arbre"),
    array("ars","artis","ciuis","f. : talent, habileté, métier, connaissance technique, art"),
    array("audacia","audaciae","uita","f. : audace, hardiesse, présomption."),
    array("aurum","auri","templum","n. : or"),
    array("auxilium","auxilii","templum","n. : aide, secours"),
    array("auaritia","auaritiae","uita","f. : cupidité, avarice"),
    array("beneficium","beneficii","templum","n. : service, bienfait"),
    array("beneuolentia","beneuolentiae","uita","f. : bienveillance, bonne volonté, dévouement"),
    array("caput","capitis","corpus","n. : tête, capitale"),
    array("carmen","carminis","corpus","n. : poème, incantation"),
    array("casus","casus","manus","m. : hasard, malheur, chute"),
    array("cena","cenae","uita","f. : cène, repas du soir"),
    array("certamen","certaminis","corpus","n. : combat, lutte, conflit"),
    array("circus","circi","amicus","m. : cirque"),
    array("clamor","clamoris","miles","m. : clameur, cri"),
    array("cliens","clientis","ciuis","m. : client"),
    array("comes","comitis","miles","m. : compagnon"),
    array("comitium","comitii","templum","n. : le comitium ; au pl. : les comices"),
    array("conuiuium","conuiuii","templum","n. : repas en commun, banquet"),
    array("copia","copiae","uita","f. : abondance, possibilité ; pl. richesses, troupes)"),
    array("cupiditas","cupiditatis","miles","f. : désir"),
    array("cura","curae","uita","f. : soin, souci"),
    array("currus","currus","manus","m. : char"),
    array("cursus","cursus","manus","m. : course, parcours, trajet"),
    array("desiderium","desiderii","templum","n. : manque, désir"),
    array("diligentia","diligentiae","uita","f. : empressement, zèle, soin scrupuleux"),
    array("discipulus","discipuli","amicus","m. : élève"),
    array("diuitiae","diuitiarum","uita","f. : richesses, biens, fortune."),
    array("dolor","doloris","miles","m. : douleur"),
    array("dominus","domini","amicus","m. : maître"),
    array("donum","doni","templum","n. : présent, cadeau"),
    array("eques","equitis","miles","m. : chevalier, cavalier"),
    array("exercitus","exercitus","manus","m. : armée"),
    array("fabula","fabulae","uita","f. : mythe, fable, pièce (de théâtre), histoire"),
    array("factum","facti","templum","n. : fait, action, travail, ouvrage"),
    array("fas","-","invaria","n. indécl. : droit divin ; - est : il est permis par les dieux de..."),
    array("nefas","-","invaria","inv. : criminel, sacrilège"),
    array("fatum","fati","templum","n. : destin, fatalité"),
    array("flamma","flammae","uita","f. : flamme"),
    array("fortuna","fortunae","uita","f. : fortune, chance"),
    array("furor","furoris","miles","m. : fureur, folie furieuse"),
    array("gaudium","gaudii","templum","n. : joie, volupté"),
    array("genus","generis","corpus","n. : race, origine, espèce"),
    array("gratia","gratiae","uita","f. : reconnaissance"),
    array("grauitas","grauitatis","miles","f. : pesanteur, sévérité, maladie"),
    array("habitus","habitus","manus","m. : manière d'être, apparence"),
    array("honor","honoris","miles","m. : honneur, hommage, magistrature"),
    array("hospes","hospitis","miles","m. : hôte"),
    array("humanitas","humanitatis","miles","f. : humanité, nature humaine"),
    array("imperium","imperii","templum","n. : pouvoir absolu"),
    array("impetus","impetus","manus","m. : mouvement en avant, élan, assaut"),
    array("industria","industriae","uita","f. : activité ; de, ex - : volontairement"),
    array("inimicus","inimici","amicus","m. : ennemi"),
    array("iniuria","iniuriae","uita","f. : injustice"),
    array("inopia","inopiae","uita","f. : pauvreté, manque"),
    array("inuidia","inuidiae","uita","f. : jalousie, envie, haine"),
    array("ira","irae","uita","f. : colère"),
    array("ius","iuris","corpus","n. : droit, autorité"),
    array("iustitia","iustitiae","uita","f. : justice"),
    array("labor","laboris","miles","m. : peine, travail, souffrance"),
    array("lacrima","lacrimae","uita","f. : larme"),
    array("laetititia","laetitiae","uita","f. : manifestation de joie, allégresse"),
    array("libertus","liberti","amicus","m. : affranchi"),
    array("litus","litoris","corpus","n. : rivage"),
    array("lucus","luci","amicus","m. : bois sacré"),
    array("ludus","ludi","amicus","m. : jeu, école"),
    array("lumen","luminis","corpus","n. : lumière, jour, éclat, pl. les yeux. dernière lettre : n"),
    array("lux","lucis","miles","f. : lumière, jour. dernière lettre : x"),
    array("magister","magistri","ager","m. : maître (d'école)"),
    array("maiores","maiorum","miles","m. : ancêtres"),
    array("manus","manus","manus","f. : main, petite troupe"),
    array("mens","mentis","miles","f. : esprit"),
    array("metus","metus","manus","m. : peur, crainte"),
    array("mons","montis","miles","m. : montagne"),
    array("mores","morum","miles","m. moeurs, genre de vie, habitudes"),
    array("mos","moris","miles","m. : coutume, manière de faire"),
    array("munus","muneris","corpus","n. :office, fonction, charge, don, présent, spectacle public"),
    array("natio","nationis","miles","f. : nation, nationalité"),
    array("natura","naturae","uita","f. : nature"),
    array("negotium","negotii","templum","n. : affaire, mission"),
    array("nemus","nemoris","corpus","n. : forêt, bois"),
    array("nobilitas","nobilitatis","miles","f. : réputation, noblesse"),
    array("numerus","numeri","amicus","m. : nombre"),
    array("oculus","oculi","amicus","m. : oeil"),
    array("odium","odii","templum","n. : haine"),
    array("officium","officii","templum","n. : service, fonction, devoir ; serviabilité ; obligation morale"),
    array("onus","oneris","corpus","n. : fardeau"),
    array("opera","operae","uita","f. : soin, effort (-am dare : se consacrer à)"),
    array("ops","opis","miles","f. : sing., pouvoir, aide ; pl., richesses"),
    array("orbis","orbis","ciuis","m. : cercle globe. - terrarum : le monde"),
    array("ordo","ordinis","miles","m. : rang, ordre, file (de soldats)"),
    array("os","ossis","corpus","n. : os"),
    array("otium","otii","templum","n. : loisir, calme, repos"),
    array("parens","parentis","ciuis","m. : parent"),
    array("patronus","patroni","amicus","m. : avocat, défenseur, patron"),
    array("paupertas","paupertatis","miles","f. : pauvreté"),
    array("pectus","pectoris","corpus","n. : poitrine, coeur, intelligence"),
    array("pecunia","pecuniae","uita","f. : argent"),
    array("periculum","periculi","templum","n. : danger, péril"),
    array("plebs","plebis","miles","f. : plèbe"),
    array("poeta","poetae","uita","m. : poète"),
    array("potestas","potestatis","miles","f. : puissance, pouvoir d'un magistrat"),
    array("praemium","praemii","templum","n. : récompense"),
    array("princeps","principis","uetus","m. : chef, empereur"),
    array("prouincia","prouinciae","uita","f. : province"),
    array("prudentia","prudentiae","uita","f. : prévoyance, prévision"),
    array("pudor","pudoris","miles","oris, m. : honte"),
    array("quies","quietis","miles","f. : tranquilité. Première lettre : q"),
    array("Quirites","Quiritum","miles","m. : les citoyens romains, quirites"),
    array("regio","regionis","miles","f. : région, arrondissement"),
    array("ripa","ripae","uita","f. : rive"),
    array("saeuitia","saeuitiae","uita","f. : fureur, violence, dureté, cruauté"),
    array("salus","salutis","miles","f. : santé, salut, conservation, action de saluer"),
    array("sanguis","sanguinis","miles","m. : sang, vigueur"),
    array("sapientia","sapientiae","uita","f. : sagesse"),
    array("scelus","sceleris","corpus","n. : crime"),
    array("sermo","sermonis","miles","m. : conversation, dialogue, discours, langue"),
    array("sol","solis","miles","m. : soleil"),
    array("sollicitudo","sollicitudinis","miles","f. : tourment, grosse inquiétude"),
    array("somnus","somni","amicus","m. : sommeil"),
    array("spectaculum","spectaculi","templum","n. : spectacle"),
    array("spes","spei","res","f. : espoir"),
    array("studium","studii","templum","n. : zèle, ardeur, intérêt, passion, étude"),
    array("superbia","superbiae","uita","f. : orgueil, fierté"),
    array("telum","teli","templum","n. : trait (javelot ou flèche)"),
    array("theatrum","theatri","templum","n. : théâtre"),
    array("triumphus","triumphi","amicus","m. : triomphe"),
    array("turba","turbae","uita","f. : foule, désordre, émoi"),
    array("umbra","umbrae","uita","f. : ombre"),
    array("usus","usus","manus","m. : usage, utilité"),
    array("utilitas","utilitatis","miles","f. : utilité"),
    array("uates","uatis","miles","m. devin, poète"),
    array("uerbum","uerbi","templum","n.  mot, parole"),
    array("uestis","uestis","ciuis","f. : vêtement"),
    array("uicinus","uicini","amicus","m. : voisin"),
    array("uinum","uini","templum","n. : vin"),
    array("uis","-","ciuis","-, f. : force"),
    array("uoluptas","uoluptatis","miles","f. : volupté"),
    array("uox","uocis","miles","f. : voix, mot"),
    array("uulgus","uulgi","amicus","n. : foule, commun des hommes"),
    array("uulnus","uulneris","corpus","n. : blessure"),
    array("uultus","uultus","manus","m. : regard, visage"),
);    
