<?php
###############################################################################
#
#    This file is part of CRVSTVLA
#
#    CRVSTVLA is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    CRVSTVLA is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with CRVSTVLA; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
###############################################################################
//*********************************************
//                  Accusatif
//*********************************************

//ad :  vers, à, près de",
$bini = array(
     array("me ad eius -rationes- adiungo.",
           "Je me joins à ses -arguments-",
           "accusatif","ratio, onis, f. : argument"),
     array("te ad -studium- summae laudis cohortabor.",
           "Je t'exhorterai à -la recherche- du plus grand mérite.",
           "accusatif","studium, ii, n. : recherche"),
     array("scribam ad te -plura- alias.",
           "Je t'en écrirai plus une autre fois.",
           "accusatif","plus, pluris, n. : plus"),
     array("sed balbi non sumus, ad -rem- redeamus.",
           "Mais nous ne sommes pas bègues, Revenons à -notre affaire-.",
           "accusatif","res, rei, f. : affaire"),
     array("Prope cottidie tibi hoc ad -forum- descendenti meditandum est: Novus sum, "
          ."consulatum peto, Roma est.",
           "À peu près tous les jours, il faut qu'en descendant au -Forum-, tu te dises : "
          ."Je suis un homme nouveau, je vise le consulat, c'est Rome.",
           "accusatif","forum, i, n. : le Forum"),
     array("uni epistulae respondi; uenio ad -alteram-.",
           "J'ai répondu à la première lettre ; je viens à -la seconde-.",
           "accusatif","alter, era, erum : autre"),
     array("cum essem in castris ad -fluuium- Pyramum, redditae mihi sunt uno "
          ."tempore a te epistulae duae",
           "Alors que j'étais au camp près du -fleuve- Pyrame, on m'apporta deux "
          ."lettres de toi à la fois.",
           "accusatif","fluuium, ii, n. : fleuve"),
     array("te rogo, si opus erit, ad -Caesarem- meam causam agas",
           "Je te demande de plaider, si besoin est, ma cause auprès de -César-.",
           "accusatif","Caesar, aris, m. : César"),
     // apud : près de, chez",
     array("cenabam apud -Seium-.",
           "Je dînais chez -Séjus-.",
           "accusatif","Seius, i, m. : Séjus"),
     array("quo tardius certior fierem de proeliis apud -Mutinam- factis, Lepidus effecit.",
           "Lépidus fit en sorte que je fusse plus tard au courant des combats qui avaient eu lieu ".
           "devant -Mutina-.",
           "accusatif","mutina, ae, f. : Mutina"),
     array("nulla minantis auctoritas apud -liberos- est.",
           "L'autorité de celui qui menace est nulle auprès des -enfants-.",
           "accusatif","liberi, orum, m. p. : enfants"),
     array("Laetus sum laudari me, inquit Hector, opinor apud -Naeuium-, abs te, pater, a laudato uiro.",
           "Je suis heureux, dit Hector, chez -Naevius- je pense, d'être loué par "
           ."toi, père, homme loué.",
           "accusatif","Naeuius, i, m. : Naevius"),
     array("Dolabella noster apud -Caesarem- est.",
           "Mon cher Dolabella est auprès de -César-.",
           "accusatif","Caesar, aris, m. : César"),
     array("ualent enim apud -Caesarem- non tam ambitiosae rogationes quam necessariae.",
           "Car aux yeux de -César-, les demandes ambitieuses n'ont pas tant de poids "
           ."que les demandes nécessaires.",
           "accusatif","Caesar, aris, m. : César"),
     array("Vide, quanti apud -me- sis.",
           "Vois quelle importance tu as pour -moi-.",
           "accusatif","ego, mei : je, me, moi"),
     // ante : devant, avant ; adv. avant",
     array("ante meum -aduentum- fama ad te de mea noua lautitia ueniet.",
           "La renommée de mon faste nouveau viendra à toi avant mon -arrivée-.",
           "accusatif","aduentus, us, m. : arrivée"),
     array("tuum tamen erga me animum agnoui multis annis ante -bellum- ciuile, cum Caesar esset in Gallia.",
           "J'ai compris tes sentiments envers moi bien des années avant -la guerre- civile, alors que "
          ."César était en Gaule.",
           "accusatif","bellum, i, n. : guerre"),
     array("equidem et ante hoc -tempus- te dilexi et semper me a te diligi sensi.",
           "Évidemment, je t'appréciais avant cette -époque-, et j'ai toujours senti que tu m'appréciais.",
           "accusatif","tempus, oris, n. : époque"),
     array("mihi ante -oculos- dies noctesque uersaris.",
           "Tu es devant -mes yeux- jours et nuits.",
           "accusatif","oculus, i, m. : oeil"),
     array("Hoc iure ante -Verrem- praetorem Siculi semper usi sunt.",
           "Les Siciliens ont toujours eu l'usage de ce droit avant que -Verrès- soit préteur.",
           "accusatif","Verres, is, m. : Verrès"),
     array("Caninius et Cato negarunt se legem ullam ante -comitia- esse laturos.",
           "Caninius et Caton déclarèrent qu'ils n'examineraient aucune loi avant les -comices-.",
           "accusatif","comitia, orum, n. p. : comices"),
     array("Senatus haberi ante -Kalendas- Februarias per legem Pupiam, id quod scis, non potest.",
           "Le Sénat ne peut se réunir avant -le premier- février en application de la "
          ."loi Pupia, vous le savez.",
           "accusatif","Kalendae, arum, f. : les calendes, le premier jour du mois"),
     // aduersus a, um : contraire ( = contre)",
     array("nec uero pietas aduersus -deos- nec quanta iis gratia debeatur sine "
          ."explicatione naturae intellegi potest.",
           "En vérité, ni la piété envers -les dieux- ni la somme de reconnaissance qu'on leur doit ne "
          ."peut être comprise sans une explication de la nature.",
           "accusatif","deus, i, m. : dieu"),
     array("etiam aduersus -infimos- iustitiam est seruandam.",
           "Même envers -les gens de la plus basse condition- il faut assurer la justice.",
           "accusatif","infimi, orum, m. p. : les gens de la plus basse condition"),
     array("aduersus -Cotum- bella gessit.",
           "Il a fait la guerre contre -Cotus-.",
           "accusatif","Cotus, i, m. : Cotus"),
     array("Antigonus in proelio, cum aduersus -Seleucum- et Lysimachum dimicaret, occisus est.",
           "Antigonus, alors qu'il combattait contre -Seleucus- et Lysimaque, fut tué pendant le combat.",
           "accusatif","Seleucus, i, m. : Seleucus"),
     array("aduersus -hominem- ingeniosum nostro ingenio usi sumus.",
           "Contre -un homme- intelligent, je me suis servi de mon intelligence.",
           "accusatif","homo, inis, m. : homme"),
     array("Sunt aduersus -morsus- quaedam adcommodata.",
           "Il y a contre -les morsures- certains remèdes appropriés.",
           "accusatif","morsus, us, m. : morsure"),
     array("Aberat ab eo Alexander stadia MD, sed iam nullum interuallum aduersus -uelocitatem- "
          ."eius satis longum uidebatur.",
           "Alexandre était éloigné de lui de 1500 stades, mais désormais aucune distance ne "
          ."paraissait assez longue contre -sa rapidité-.",
           "accusatif","uelocitas, atis, f. : rapidité"),
     // cis : en deçà",
     // citra : en deçà de, contrairement à",
     // circum : autour de",
     // circa : autour de",
     // contra : contre",
     array("quid enim est, quod contra -uim- sine ui fieri possit?",
           "Qu'y a-t-il, alors, qu'on puisse faire contre -la violence- sans violence ?",
           "accusatif","uis, - : violence"),
     array("contra importunissimos -latrones- arma cepi.",
           "J'ai pris les armes contre de très cruels -brigands-.",
           "accusatif","latro, onis, m. : brigand"),
     array("nos hic cum Antonio bellum gerimus, sed non pari condicione, contra -arma- uerbis.",
           "Nous sommes ici en guerre avec Antoine, non pas à égalite, mais avec des paroles, "
           ."contre -des armes-.",
           "accusatif","arma, orum, n. : armes"),
     array("atque haec ego idcirco ad te contra -consuetudinem- meam pluribus scripsi.",
           "Et c'est pour cette raison que, contrairement à mon -habitude-, je t'ai écrit assez longuement.", 
           "accusatif","consuetudo, dinis, f."),
     // erga : devant, en face de",
     array("rex Deiotarus, uir cum beneuolentia et fide erga -populum- Romanum singulari"
          ."legatos ad me misit.",
          "Le roi Deioratus, homme d'une bienveillaince et d'une fidélité remarquables envers -le peuple- ".
          "romain, m'a envoyé des ambassadeurs.",
          "accusatif","populus, i, m. : peuple"),
     array("quare uelim pro tua perpetua erga -me- beneuolentia scribas ad me.",
           "Aussi voudrais-je que, en vertu de ton indéfectible bienveillance envers -moi-, tu m'écrives.",
           "accusatif","ego, mei : je, me, moi"),
     array("neque enim de meo erga -te- studio dubitare debes.",
           "Et tu ne dois pas douter de mon attachement pour -toi-.",
           "accusatif","tu, tui : tu, te, toi"),
     array("Agit hominibus gratias et eorum beniuolentiam erga -se- diligentiamque conlaudat. (Verres)",
           "Il congratule ces hommes, et les loue de leur bienveillance et de leur empressement pour -lui-.",
           "accusatif","se, sui : pronom réfl. 3e pers."),
     // extra : en dehors de",
     array("sed mehercules extra -iocum- homo bellus est.",
           "Mais ma foi, -plaisanterie- mise à part, c'est un home spirituel.",
           "accusatif","iocus, i, m. : plaisanterie"),
     array("eum non facile non modo extra tectum, sed ne extra -lectum- quidem quisquam uidit",
           "On ne l'a jamais vu facilement non seulement hors de chez lui, "
           ."mais encore hors même de son -lit-.",
           "accusatif","lectus, i, m. : lit"),
     array("nostis extra -portam- Collinam aedem Honoris.",
           "Tu connais, au delà de -la porte- Colline, le temple d'Honos.",
           "accusatif","porta, ae, f. : porte"),
     array("quaedamque serpentes ortae extra -aquam- simul ac primum niti possunt aquam persequuntur.",
           "Certains serpents, nés hors de -l'eau-, dès qu'ils peuvent faire cet effort, recherchent l'eau.",
           "accusatif","aqua, ae, f. : eau"),
     // inter : parmi, entre",
     array("neque haec incerta tamen uulgo iactantur, sed inter -paucos-, quos tu nosti, "
          ."palam secreto narrantur.",
           "Et pourtant ces événements incertains ne circulent pas en public, mais sont clairement "
          ." racontés en secrets parmi -quelques personnes-, que toi, tu connais.",
           "accusatif","pauci, orum, m. : quelques uns"),
     array("Pacis inter -ciues- conciliandae te cupidum esse laetor.",
           "Je suis heureux que tu sois désireux de ménager un accord de paix entre -les citoyens-.",
           "accusatif","ciuis, is, m. : citoyen"),
     array("quem locum uolo tibi esse notum: iacet inter -Appenninum- et Alpes, impeditissimus "
     ."ad iter faciendum.",
           "Je veux que ce lieu soit connu de toi : d'un accès fort malaisé, il est situé entre "
          ."-l' Apennin-, et les Alpes.",
           "accusatif","Appenninus, i, n. : Apennin"),
     array("inter -feras- satius est aetatem degere quam in hac tanta immanitate uersari.",
           "Mieux vaut passer sa vie parmi -les bêtes sauvages- que de se trouver dans une telle inhumanité.",
           "accusatif","fera, ae, f. : bête sauvage"),
     array("At quid interest inter periurum et -mendacem- ?",
           "Mais quelle est la différence entre un parjure et -un menteur- ?",
           "accusatif","mendax, acis, m. : menteur"),
     array("nulla uox alia illius miseri inter -dolorem- crepitumque plagarum audiebatur nisi haec : "
          ."Ciuis Romanus sum.",
           "Au milieu de -la douleur- et du crépitement des coups, on n'entendait pas d'autre parole "
          ."que celle-ci : Je suis Citoyen Romain.",
           "accusatif","dolor, oris, m. : douleur"),
     array("L. Cotta, etsi damnatus est, mihi uidetur tamen inter -uiros- optimos atque "
     ."innocentissimos esse numerandus.",
           "Lucius Cotta, bien qu'ayant été condamné, m'apparaît comme devant être compté au nombre "
          ."des -hommes- les meilleurs et les plus innocents.",
           "accusatif","uir, uiri, m. : homme"),
     // intra : au-dedans, à l'intérieur de",
     array("locum sepulturae intra -urbem- ut darent, impetrare non potui.",
           "Je n'ai pu obtenir qu'ils accordent pour sa sépulture un emplacement "
          ."à l'intérieur de -la ville-.",
           "accusatif","urbs, urbis, f. : ville"),
     array("ducem hostium intra -moenia- atque adeo in senatu uidetis.",
           "Vous voyez le chef de nos ennemis à l'intérieur des -remparts-, et même au sénat.",
           "accusatif","moenia, ium, n. : remparts"),
     array("sed non possum non exhorrescere si quid intra -cutem- subest uulneris.",
           "Mais je ne peux pas ne pas frissonner s'il y a sous -la peau- quelque chose de la blessure.",
           "accusatif","cutis, is, f. : peau"),
     array("intra -annum- uero uicesimum feminae notitiam habuisse in turpissimis habent rebus. (Caes)",
           "Au contraire, ils considèrent comme faisant partie des choses les plus honteuses "
          ."que d'avoir connu une femme avant sa vingt-et-unième -année-.",
           "accusatif","annus, i, m. : année"),
     // infra : au-dessous de, en bas de",
     // iuxta : à côté de",
     // ob : à cause de",
     array("Quam ob -causam- ? Nescio.",
           "Pour quelle -cause- ? Je ne sais pas.",
           "accusatif","causa, ae, f. : cause"),
     array("Quam ob -rem- si iure posses eum accusare, tamen id pie facere non posses.",
           "C'est pour-quoi- même si tu pouvais l'accuser à bon droit, tu ne pourrais quand même "
          ."pas le faire sans être impie.",
           "accusatif","res, rei, f. : chose"),
     array("At eum tu ob -uirtutem- corona ante donaras.",
           "Mais tu lui avais auparavant attribué une couronne pour -sa vertu-.",
           "accusatif","uirtus, utis, f. : vertu"),
     array("Credibile est igitur tantum facinus nullam ob -causam- esse commissum ?",
           "Est-il donc croyable qu'un tel crime ait été commis sans aucune -cause- ?",
           "accusatif","causa, ae, f. : cause"),
     // pone : derrière",
     // per : à travers, par",
     array("Lentulo nostro egi per -litteras- tuo nomine gratias diligenter;",
           "Je me suis empressé de remercier par -lettre- en ton nom notre cher Lentulus.",
           "accusatif","litterae, arum, f. p. : lettre"),
     array("iter in Ciliciam facio per -Cappadociam-.",
           "Je voyage en Cilicie en passant par la -Cappadoce-.",
           "accusatif","Cappadocia, ae, f. : Cappadoce"),
     array("nunc cum cohortibus mihi per -niues- eundum est.",
           "Maintenant, je dois avancer à travers -les neiges- avec mes cohortes.",
           "accusatif","nix, niuis, f. : neige"),
     array("tamen te penitus rogo, ne te tam longae nauigationi et uiae per -hiemem- nisi bene "
          ."firmum committas.",
           "Je te demande tout de même instamment de ne pas te lancer dans une traversée et "
          ."une route si longs pendant -l'hiver-, sans être en bonne santé.",
           "accusatif","hiems, hiemis, f. : hiver"),
     array("Curre, per deos atque -homines- !",
           "Cours, par les dieux et -les hommes- !",
           "accusatif","homo, minis, m. : homme"),
     array("Recede de medio; per -alium- transigam.",
           "Ôte-toi du milieu, je concluerai l'affaire par l'intermédiaire d'-un autre-",
           "accusatif","alius, alia, aliud : autre"),
     array("Siciliam -prouinciam- C. Verres per triennium depopulatus est.",
           "Caius Verres a pillé -la province- de Sicile tout au long de trois années.",
           "accusatif","prouincia, ae, f. : province"),
     // prope  : près de",
     // secundum : après, derrière, selon, suivant, conformément à",
     array("Marcellus duo uulnera accepit, unum in stomacho, alterum in capite secundum -aurem-.",
           "Marcellus a reçu deux blessures, l'une à l'estomac, l'autre à la tête, derrière -l'oreille-.",
           "accusatif","Marcellus, i, m. : Marcellus"),
     array("Finem bonorum dicebant secundum -naturam- uiuere.",
           "Ils disaient que le but des gens de bien était de vivre selon -la nature-.",
           "accusatif","natura, ae, f. : nature"),
     array("Tum  secundum -quietem- uisus ei dicitur draco.",
           "On dit qu'alors, pendant -son sommeil-, lui est apparu un dragon ",
           "accusatif","quies, etis, f. : sommeil"),
     array("secundum -te- nihil est mihi amicius solitudine.",
           "Selon  -toi-, je n'ai pas de meilleur ami que la solitude.",
           "accusatif","tu, tui : tu, te, toi"),
     // post : après",
     array("hoc post hominum -memoriam- contigit nemini.",
           "De -mémoire- d'homme, cela n'est arrivé à personne.",
           "accusatif","memoria, ae, f. : mémoire"),
     array("erat res post natos -homines- pulcherrima.",
           "C'était la plus belle chose depuis la naissance des hommes (depuis -les hommes- nés)",
           "accusatif","homo, minis, m. : homme"),
     array("nos post -reges- exactos seruitutis obliuio ceperat.",
           "L'oubli de la servitude nous avait pris depuis l'expulsion des rois (-les rois- chassés).",
           "accusatif","rex, regis, m. : roi"),
     array("hic, qui in conlegio sacerdotum esset, primus post -Romam- conditam iudicio "
          ."publico est condemnatus.",
           "Cet homme, qui faisait partie du collège des prêtres, fut le premier condamné en public "
          ."depuis la fondation de Rome (depuis -Rome- fondée).",
           "accusatif","Roma, ae, f. : Rome"),
     array("post magnum illud Peloponnesiacum -bellum- triginta uiri illi urbi "
     ."iniustissime praefuerunt.",
           "Après cette grande -guerre- du Péloponèse, trente hommes gouvernèrent injustement cette ville.",
           "accusatif","bellum, i, n. : guerre"),
     array("mihi nuntiauit M. Marcellum post cenae -tempus- a P. Magio Cilone, familiare eius, "
          ."pugione percussum esse.",
           "Il m'annonce qu'après -le temps- du dîner, Marcus Marcellus avait été poignardé par "
          ."Paulus Magius Cilo, son ami.",
           "accusatif","tempus, oris, n. : temps"),
     array("is post -proelium- se ad hominem necessarium, A. Plautium, in Bithyniam contulit.",
           "Après -le combat-, il s'est retiré en Bithynie auprès de son ami intime Aulus Plautius.",
           "accusatif","proelium, ii, n. : combat"),
     // trans : de l'autre côté",
     array("tuae res gestae ita notae sunt ut trans -montem- Taurum etiam de Matrinio sit auditum.",
           "Tes exploits sont si connus que même de l'autre côté du -mont- Taurus on "
          ."entend parler de Matrinius.",
           "accusatif","mons, montis, m. : mont"),
     array("Pompeius trans -flumen- Apsum positis castris eo copias omnes auxiliaque conduxit.",
           "Pompée, ayant installé son camp sur l'autre rive du -fleuve- Apsus, y conduisit "
          ."toutes ses troupes et les forces alliées.",
           "accusatif","flumen, minis, n. : fleuve"),
     array("trans -Tiberim- longe cubat is prope Caesaris hortos.",
           "Il habite loin, de l'autre côté du -Tibre-, près des jardins de César.",
           "accusatif","Tiberis, is, m. : Tibre"),
     array("caelum, non animum mutant, qui trans -mare- currunt.",
           "Ils changent leur ciel, non leur âme, ceux qui courent au-delà de -la mer-.",
           "accusatif","mare, maris, n. : mer"),
     array("gladium in publicum trans -maceriam- horti abiecit.",
           "Il a jeté le glaive sur la voie publique, de l'autre côté de -la clôture- du jardin.",
           "accusatif","maceria, ae, f. : clôture"),
     // ultra : plus loin que, plus que",
     array("nihil est enim ultra illam -altitudinem- montium usque ad Oceanum quod "
     ."sit Italiae pertimescendum.",
           "Car il n'y a rien, après cette -altitude- des monts jusqu'à l'Océan, qui soit "
          ."à craindre par l'Italie.",
           "accusatif","altitudo, dinis, f. : altitude"),
     array("Cottae quod negas te nosse, ultra Silianam -uillam- est, uillula sordida et ualde pusilla.",
           "La villa de Cotta, que tu dis ne pas connaître, est après -la villa- de Silianus, une petite "
          ."villa sale, et vraiment toute petite.",
           "accusatif","uilla, ae, f. : villa"),
     array("frigida aqua copiose praestanda est, ut bibat etiam ultra -satietatem-.",
           "Il faut lui servir abondamment de l'eau froide pour qu'il boive, même au-delà de -la sasiété-.",
           "accusatif","sasietas, atis, f. : sasiété"),
     array("Nihil ultra -hereditatem- petere debes.",
           "Tu ne dois rien demander en plus de -l'héritage-.",
           "accusatif","hereditas, atis, f. : héritage"),
     // praeter  : devant, le long de, au-delà de, excepté",
     array("hoc quis ante te, quis praeter -te-, fecerit quaero.",
           "je demande qui avant toi, qui à part -toi-, a fait cela.",
           "accusatif","tu, tui : tu, te, toi"),
     array("Quae est enim praeter -Sardiniam- prouincia quae nullam habeat amicam populo Romano "
     ."ac liberam ciuitatem ?",
           "Quelle province, exceptée -la Sardaigne-, n'a aucune ville amie du peuple romain, et libre ?",
           "accusatif","Sardinia, ae, f. : Sardaigne"),
     array("Obstabat eius cogitationibus nemo praeter -Milonem-.",
           "Personne ne s'opposait à ses desseins, si ce n'est -Milon-.",
           "accusatif","Milo, onis, m. : Milon"),
     array("Quid est in Antonio praeter -libidinem-, crudelitatem, petulantiam, audaciam ?",
           "Qu'y a-t-il chez Antoine, sinon -la débauche-, la cruauté, l'arrogance, l'audace.",
           "accusatif","libido, dinis, f. : débauche"),
     array("Hoc ita praeter -exspectationem- accidit, ut testem omnium risus obrueret. (confondre un témoin)",
           "Il arriva, contre toute -attente-, que le rire général confondit le témoin.",
           "accusatif","exspectatio, onis, f. : attente"),
     array("nullum est animal praeter -hominem- quod habeat notitiam aliquam dei.",
           "Il n'est aucun animal qui ait la moindre notion de dieu, sauf -l'homme-.",
           "accusatif","homo, minis, m. : homme"),
     array("praeter uitia atque -uirtutes- negauit rem esse ullam aut fugiendam aut expetendam.",
           "Il déclara qu'à part les vices, rien ne devait être évité, et à part -les vertus-, rien "
          ."ne devait être recherché.",
           "accusatif","uirtus, utis, f. : vertu"),
     // propter : à cause de, à côté",
     array("putant oportere defendi, defendere ipsi propter -iniquitatem- temporum non audent.",
           "Ils pensent qu'il faut être défendu, ils n'osent pas se défendre soi-même à cause "
          ."de -l'injustice- des temps (de l'injustice actuelle).",
           "accusatif","iniquitas, atis, f. : iniquité"),
     array("Quid igitur fugiebant ? Propter -metum-.",
           "Pourquoi donc fuyaient-ils ? Par -peur-.",
           "accusatif","metus, us, m. : peur"),
     array("Hanc mihi tu si propter meas -res- gestas imponis in omni uita mea, Torquate, "
     ."personam, uehementer erras.",
           "Si tu me fais porter ce masque à cause de mes -actions- dans toute ma vie, "
          ."Torquatus, tu te trompes lourdement.",
           "accusatif","res, rei, f. : action"),
     array("At enim non nulli propter -timorem-, quod se in senatu tuto non esse "
          ."arbitrabantur, discesserunt.",
           "Alors, en effet, quelques une s'éloignèrent par -crainte-, parce qu'ils ne se sentaient "
          ."pas en sûreté au sénat.",
           "accusatif","timor, oris, m. : crainte"),
     array("Sperauit, credo, difficilis tibi Alexandreae fore exitus propter regionum "
          ."-naturam- et fluminis.",
           "Il espérait, je crois, qu'il te serait difficile de sortir d'Alexandrie à cause de la "
          ."-nature- des lieux et du fleuve.",
           "accusatif","natura, ae, f. nature"),
     array("O beatos illos qui, cum adesse ipsis propter -uim- armorum non licebat, aderant tamen !",
           "Oh heureux ceux qui, bien qu'il ne leur fût pas permis d'être là à cause de -la force- des "
          ."armes, étaient pourtant là !",
           "accusatif","uis, -, f. force"),
     array("tum in pratulo propter Platonis -statuam- consedimus.",
           "Alors nous nous assîmes sur un petite pelouse, non loin d'-une statue- de Platon.",
           "accusatif","statua, ae, f. : statue"),
     // supra : au dessus de, au delà de",
     array("ibi pugnatum. supra septem -milia- hostium caesa, alii fugati; praeda parta ingens.",
           "La bataille fut livrée là. Plus de sept -milliers- d'ennemis furent tués, les autres "
          ."mis en fuite ; un butin considérable partagé.",
           "accusatif","millia, ium : milliers"),
     array("cum exercitu omni profectus supra -Suessulam- castris positis consedit.",
           "Parti avec toute son armée il s'établit après avoir planté son camp au-dessus de -Suessula-.",
           "accusatif","Suessula, ae, f. : Suessula"),
     array("Crispinus supra -scutum- sinistrum umerum Badio hasta transfixit,",
           "Crispinus tranperça de sa hache l'épaule gauche de Badius, au-dessus du -bouclier-.",
           "accusatif","scutum, i, n. : bouclier"),
     array("Trimalchio ne uideretur iactura motus, basiauit puerum ac iussit "
          ."supra -dorsum- ascendere suum.",
          "Trimalchion, pour ne pas paraître ému de cette perte, embrassa le jeune esclave "
          ."et le fit monter sur -son dos-.",
                "accusatif","dorsum, i, n. : dos"),
     //usque ad : jusqu'à",
     array("Hac controuersia usque ad -noctem- ducta senatus dimissus est.",
           "Cette controverse s'étant prolongée jusqu'à -la nuit-, la séance du sénat fut levée.",
           "accusatif","nox, noctis, f. : nuit"),
     array("ille nihil difficilius esse dicebat, quam amicitiam usque ad extremum "
     ."uitae -diem- permanere.",
           "Il disait que rien n'était plus rare qu'une amitié qui demeure jusqu'au "
          ."dernier -jour- de la vie.",
           "accusatif","dies, ei, m. ou f. : jour"),
     array("Quis enim ignorat eos usque ad hanc -diem- retinere illam immanem ac "
          ."barbaram consuetudinem hominum immolandorum ?",
           "Qui ignore, en effet, qu'ils ont conservé jusqu'à ce -jour- la coutume inhumaine "
          ."et barbare du sacrifice humain ?",
           "accusatif","dies, ei, m. ou f. : jour"),
     // penes : en possession de"
// *********************************************
//                     Ablatif
// *********************************************
     //"ab : à partir de, après un verbe passif = par",
     array("multae mihi a C. -Verre- insidiae terra marique factae sunt.",
           "De nombreux pièges mont été tendus par Caius -Verrès-, sur terre et sur mer.",
          "ablatif","Verres, is, m. : Verrès"),
     array("hora nulla uacua a -furto-, scelere, crudelitate, flagitio reperietur.",
           "On ne trouvera aucune heure vide de -vol-, crime, cruauté, turpitude.",
           "ablatif","furtum, i, n. : vol"),
     array("Ipse Sulla, cui aduentus istius gratissimus esse debuit, ab se hominem "
          ."atque ab -exercitu- suo remouit.",
           "Même Sylla, pour qui l'arrivée de cet homme aurait dû être très agréable, "
          ."mit cet homme à l'écart de lui-même et de son -armée-.",
           "ablatif","exercitus, us, m. : armée"),
     array("Scelus est accipere ab -reo- : quanto magis ab accusatore, quanto etiam sceleratius ab utroque !",
           "Il est criminel de recevoir de l'argent d'-un accusé- ; d'autant plus criminel d'en recevoir "
          ."d'un accusateur, et d'autant plus criminel encore d'en recevoir des deux !",
           "ablatif","reus, rei, m. : accusé"),
     array("Ex agro homines traducis in forum, ab -aratro- ad subsellia, ab usu rerum "
     ."rusticarum ad insolitam litem atque iudicium ?",
           "Tu fais comparaître au forum des hommes des champs, de -la charrue- au tribunal, de occupations "
          ."de la vie rustique à une audience inhabituelle et à un procès ?",
           "ablatif","aratrum, i, n. : charrue"),
     array("Herculis templum est apud Agrigentinos non longe a -foro-, sane sanctum "
          ."apud illos et religiosum.",
           "Chez les Agrigentins, il y a le temple d'Hercule, non loin -du forum-, lieu hautement saint et "
          ."vénérable pour eux.",
           "ablatif","forum, i, n. : forum"),
     array("sagittae pendebant ab -umero-, sinistra manu retinebat arcum, dextra ardentem facem praeferebat.",
           "Les flèches pendaient de -l'épaule-, de la main gauche il tenait un arc, de la droite il "
          ."tendait un flambeau allumé.",
           "ablatif","umerus, i, m. : épaule"),
    //"abs : par, de",
    // "cum : avec",
     array("Hortensius consul designatus domum reducebatur e campo cum maxima frequentia ac -multitudine-.",
           "Le consul Hortensius, désigné, était reconduit du Champ de Mars chez lui au milieu d'une "
          ."-foule- très dense et très nombreuse.",
           "ablatif","multitudo, dinis, f. : foule"),
     array("Erit tum consul Hortensius cum summo -imperio- et potestate.",
           "Hortensieus sera alors consul, avec le -pouvoir- et la puissance suprêmes.",
           "ablatif","imperium, i, n. : pouvoir"),
     array("eius erat filiam, quae cum -patre- habitaret propterea quod uirum non habebat.",
           "C'était sa fille, qui habitait avec -son père- parce qu'elle n'avait pas de mari.",
           "ablatif","pater, tris, m. : père"),
     array("Vidi argenteum Cupidinem cum -lampade-.",
           "J'ai vu un Cupidon d'argent avec -un flambeau-.",
           "ablatif","lampas, adis, f. : flambeau"),
     array("Cognoscite pactiones Menaenorum cum Venerio -seruo-.",
           "Apprenez les accords des habitants de Mènes avec -son esclave- Venerius.",
           "ablatif","seruus, i, m. : esclave"),
     array("Querebantur cum -luctu- et gemitu aratores : tu id nesciebas ?",
           "Les laboureurs se plaignaient avec -douleur- et en gémissant : toi, tu ignorais cela ?",
           "ablatif","luctus, us, m. : douleur"),
     array("Illo tempore Segestanis maxima cum -cura- haec ipsa Diana, de qua dicimus, redditur.",
           "En ce temps-là cette même Diane, dont j'ai parlé, est rendue aux Ségestion avec la plus grande "
          ."-ponctualité-.",
           "ablatif","cura, ae, f. : ponctualité"),
     //  "coram  : devant, publiquement",
     //  "de : au sujet de, du haut de, de",
     array("qua de -re- controuersia est ?",
           "À quel -sujet- y a-t-il contestation ?",
           "ablatif","res, rei, f. : chose"),
     array("Possumus aliquando depositis armis sine -periculo- fortunarum de -re- pecuniaria disceptare ?",
           "Pouvons nous jamais, après avoir déposé les armes, sans risque pour nos biens, débattre au "
          ."sujet de l'argent (au sujet de -la chose- pécuniaire) ?",
           "ablatif","res, rei, f. : chose"),
     array("Nihil a me de pueritiae suae -flagitiis- audiet,",
           "Il n'apprendra rien de moi au sujet des -fautes- de son enfance.",
           "ablatif","flagitium, ii, n. : faute"),
     array("Flebat uterque non de suo -supplicio-, sed pater de fili morte, de patris filius.",
           "Chacun pleurait, non sur son propre -supplice-, mais un père sur la mort de son fils, "
          ."un fils sur celle de son père.",
           "ablatif","supplicium, ii, n. : supplice"),
     array("Nauem tu de -classe- populi Romani ausus es uendere ?",
           "Tu as ausé, toi, vendre un bâtiment de -la flotte- du peuple romain ?",
           "ablatif","classis, is, f. : flotte"),
     array("Si pupillo opus redimitur, mihi praeda de -manibus- eripitur.",
           "Si l'oeuvre est rachetée à l'héritier mineur, cette proie est arrachée de -mes mains-.",
           "ablatif","manus, us, f. : main"),
     array("quid porro argumenter, qua de -re- dubitare nemo possit?",
           "À quoi bon argumenter plus sur -une chose- dont personne ne peut douter ?",
           "ablatif","res, rei, f. : chose"),
     array("Quam multis istum putatis hominibus honestis de -digitis- anulos abstulisse ?",
           "À combien de gens honnêtes pensez-vous qu'il ait retiré les anneaux de -leurs doigts- ?",
           "ablatif","digitus, i, m. : doigt"),
     //  "e, ex : hors de, de",
     array("audacissimus ego ex -omnibus- ?",
           "Suis-je le plus audacieux de -tous- ?",
           "ablatif","omnis, e : tout, tous"),
     array("Vt primum e -prouincia- rediit, redemptio est huius iudici facta grandi pecunia.",
           "Aussitôt rentré de -sa province-, il racheta (l'acquitement de) ce jugement à grands frais.",
           "ablatif","prouincia, ae, f. : province"),
     array("Erant signa ex -aere- complura.",
           "Il y avait de très nombreuses statues de -bronze-.",
           "ablatif","aes, aeris, n. : bronze"),
     array("Quonam se uerteret ? ex quo -fructu- nummos quos tibi daret inueniret ?",
           "Vers où se tourner ? de quel -revenu- tirerait-il l'argent à te donner ?",
           "ablatif","fructus, us, m. : revenu"),
     array("Erat etiam uas uinarium, ex una -gemma- pergrandi trulla excauata.",
           "Il y a vait aussi une carafe à vin, une louche taillée d'une pièce dans une -pierre précieuse- "
          ."de grande taille.",
           "ablatif","gemma, ae, f. : pierre précieuse"),
     array("Itaque breui tempore ad fanum ex -urbe- tota concurritur.",
           "C'est pourquoi en peu de temps, de -la ville-, on accourt vers le sanctuaire.",
           "ablatif","urbs, urbis, f. : ville"),
     array("Hanc rem nuntiat M. Tullio Philinus, qui grauiter saucius e -caede- effugerat.",
           "Philinus, qui s'était enfui du -massacre- gravement blessé annonce cela à Marcus Tullius.",
           "ablatif","caedes, is, f. : massacre"),
     //  "pro : devant, pour, à la place de, en considération de",
     array("Mancipes a ciuitatibus pro -frumento- pecuniam exegerunt.",
           "Les percepteurs exigèrent des cites de l'argent en échange du -blé-.",
           "ablatif","frumentum, i, n. : blé"),
     array("e complexu parentum abreptos filios ad necem ducebat, et parentis pretium pro "
          ."-sepultura- liberum poscebat.",
           "Il arrachait les fils des bras de leurs parents, les conduisait à la mort, et "
          ."réclamait le paiement des parents pour -la sépulture- des enfants.",
           "ablatif","sepultura, ae, f. : sépulture"),
     array("Siciliae prouinciae, cum esses pro -consule-, praefuisti.",
           "Tu as été à la tête de la province de Sicile, Lorsque tu y étais en qualité de pro-consul-.",
           "ablatif","consul, ulis, m. : consul"),
     array("eam legem pro -plebe-, non in plebem tulit.",
           "Il a fait passer cette loin en faveur de -la plèbe-, non contre la plèbe.",
           "ablatif","plebs, plebis, f. : plèbe"),
     //  "prae : devant, à cause de",
     array("nec loqui prae -maerore- potuit!",
           "Il n'a pas pu parler à cause de -son chagrin-.",
           "ablatif","maeror, oris, m. : chagrin"),
     array("Cupiebam mehercule longiorem epistulam facere, sed nec erat res de qua scriberem "
     ."nec iocari prae -cura- poteram.",
           "Je désirais, parbleu, faire une lettre plus longue, mais je n'avais plus rien au sujet de"
          ."quoi t'écrire, et je ne pouvais pas plaisanter à cause de mon -souci-.",
           "ablatif","cura, ae, f. : souci"),
     array("neminem prae -se- ducit hominem.",
           "Il croit qu'aucun homme n'est devant -lui-.",
           "ablatif","se, sui : soi, lui-même"),
     array("solem prae iaculorum -multitudine- et sagittarum non uidebitis",
           "Vous ne verrez pas le soleil à cause de -la multitude- de nos javelots et de nos flèches.",
           "ablatif","multitudo, dinis, f. : multitude"),
     //  "palam : en présence de, devant",
     //  "sine : sans",
     array("At sine summo -scelere- P. Quinctium, propinquum tuum, iugulare non potes.",
           "Mais tu ne peux pas, sans -crime- de la plus grande gravité, étrangler Paulus Quinctius, "
          ."qui fait partie de ta famille.",
           "ablatif","scelus, eris, n. : crime"),
     array("qui tantum facinus commiserunt non modo sine cura quiescere sed ne spirare "
     ."quidem sine -metu- possunt.",
           "Ceux qui ont commis un tel forfait ne peuvent non seulement prendre du repos sans souci, "
          ."mais encore respirer sans -peur-.",
           "ablatif","metus, us, m. : peur"),
     array("tum erat ager incultus sine -tecto-, nunc est cultissimus cum optima uilla.",
           "C'était alors une friche sans -toit- ; c'est maintenant un terrain complètement cultivé "
          ."avec une magnifique villa.",
           "ablatif","tectum, i, n. : toit"),
     array("Videt sine -lege- curiata nihil agi per xuiros posse.",
           "Il voit que sans -loi- curiate, rien ne peut être fait par l'intermédiaire des decemvirs.",
           "ablatif","lex, legis, f. : loi"),
     array("Quid est uobis consulibus gestum sine -armis- ?",
           "Quelle mesure, sous votre consulat, a été appliquée sans -les armes- ?",
           "ablatif","arma, orum, n. : armes"),
     array("Ego autem sine iracundia dico omnia nec tamen sine -dolore- animi.",
           "En ce qui me concerne, je dis tout sans colère et pourtant sans -douleur- morale.",
           "ablatif","dolor, oris, m. : douleur"),
     array("habet enim multitudo uim quandam talem, ut, quem ad modum tibicen sine -tibiis- canere, "
     ."sic orator sine multitudine audiente eloquens esse non possit.",
           "Car la foule a une certaine force, telle que, tout comme le flûtiste ne peut jouer sans "
          ."-ses flûtes-, l'orateur ne peut être éloquent sans la foule qui l'écoute.",
           "ablatif","tibia, ae f. : flûte"),
     //  "absque : sans, excepté, loin de",
     //  "tenus : jusqu'à"
// *********************************************
//           ou Ablatif
// *********************************************
     //  "in : dans, sur, contre (lieu où l'on va) : dans, sur (lieu où l'on est)",
     array("IN C. -VERREM- ACTIO PRIMA",
           "PREMIÈRE PLAIDOIERIE CONTRE CAIUS -VERRÈS-",
           "accusatif","Verres, is, m. : Verrès"),
     array("in -Galliam- proficiscitur Quinctius",
           "Quinctius part en -Gaule-.",
           "accusatif","Gallia, ae, f. : Gaule"),
     array("Legati in -castra- ueniunt.",
           "Les ambassadeurs viennent dans -le camp-.",
           "accusatif","castra, orum, n. : camp militaire"),
     array("Venit ipse in -aedem- Castoris, considerat templum.",
           "Il vient lui-même dans -le temple- de Castor, il considère le sanctuaire.",
           "accusatif","aedes, is, f. : temple"),
     array("nam istum exheredare in -animo- habebat.",
           "Il avait en effet dans l'esprit (l'intention) de le déshériter.",
           "ablatif","animus, i, m. : esprit"),
     array("Anseribus cibaria publice locantur et canes aluntur in -Capitolio- "
     ."ut significent si fures uenerint.",
           "De la nouriture pour les oies est disposée aux frais de l'état, et des chiens sont nourris "
          ."sur -le Capitole- pour qu'ils avertissent si des voleurs viennent.",
           "ablatif","Capitolium, ii, n. : Capitole"),
     array("omnia in unius potestate ac -moderatione- uertentur.",
           "tout est placé en le pouvoir et sous -l'administration- d'un seul.",
           "ablatif","moderatio, onis, f. : administration"),
     array("Aspendum uetus oppidum et nobile in -Pamphylia- scitis esse, plenissimum signorum optimorum.",
           "Aspendum, comme vous le savez, est une vieille ville illustre en Pamphylie, où abondent "
          ."les oeuvres d'art les plus remarquables.",
           "ablatif","Pamphylia, ae, f. : Pamphylie"),
     //  "sub : sous, de dessous, immédiatement après, au moment de 
     //         sous, aux environs de, vers la même époque que ",
     array("Non mediocris res neque paruum sub hoc -uerbo- furtum, Quirites, latet.",
           "Sous ce -mot-, le vol, Quirites, se cache une chose ni ordinaire, ni insignifiante.",
           "ablatif","uerbum, i, n. : mot"),
     array("Desunt omnino ei populo multa, qui sub -rege- est, in primisque libertas",
           "Au peuple qui est soumis à -un roi-, manquent complètement beaucoup de choses, et, parmi les "
          ."plus importantes, la liberté.",
           "ablatif","rex, regis, m. : roi"),
     array("saepe est etiam sub -palliolo- sordido sapientia.",
           "Souvent, même sous un -petit manteau- crasseux, il y a la sagesse.",
           "ablatif","palliolum, i, n. : petit manteau"),
     array("ego ausus sum dicere, pacem ipsam, quoniam sub -nomine- pacis bellum lateret, repudiandam;",
           "J'ai osé, moi, dire que la paix même, puisque sous -le nom- de paix se cachait la guerre, "
          ."devait être refusée.",
           "ablatif","nomen, inis, n. : nom"),
     array("Senatus fuit frequentior quam putabamus esse posse mense Decembri sub -dies- festos.",
           "Le sénat fu plus fréquenté que nous pensions qu'il pût l'être au mois de décembre, "
          ."à l'époque des -jours- de fête.",
           "accusatif","dies, ei, m. ou f. : jour"),
     array("L. Mummius urbes Achaiae Boeotiaeque multas sub -imperium- populi "
          ."Romani -dicionemque- subiunxit.",
           "Lucius Mummius réduisit de nombreuses viles d'Achaïe et de Béotie sous la puissance et "
          ."-domination- du peuple romain.",
           "accusatif","dicio, onis, f. : domination"),
     array("numquam sub legum et iudiciorum -potestatem- casurum esse duxisti ?",
           "tu pensais ne jamais tomber sous -la puissance- des lois et des jugements ?",
           "accusatif","potestas, atis, f. : puissance"),
     //  "super : sur, au-dessus de, au-delà de, pendant : sur, au-dessus de, en plus de, au sujet de ",
     array("qui circa Alexandrum erant uidisse se crediderunt paulum super -caput- regis placide "
     ."uolantem aquilam.",
           "Ceux qui étaient autour d'Alexandre crurent voir un peu au-dessus de -la tête- du roi"
          ."un aigle volant paisiblement.",
           "accusatif","caput, itis, n. : tête"),
     array("super amici -corpus- procubuit exanimis.",
           "Il tomba sans vie sur le -corps- de son ami.",
           "accusatif","corpus, oris, n. : corps"),
     array("constitit ipse super ramoso -stipite- nixus.",
           "Il s'arrêta lui-même, appuyé sur -un tronc- branchu.",
           "ablatif","stipes, pitis, m. : tronc")
     //  "subter : sous, au pied de : sous, au pied de (poétique)"
     //"clam : à l'insu de 
);
