<?php
$lex = array(
array("aedificium","aedifici","templum","n","ii, n. : l'édifice"),
array("aeuum","aeu","templum","n","i, n. : époque, durée, âge"),
array("argumentum","argument","templum","n","i, n. : argument, preuve, matière, sujet"),
//array("arma","ar","templum","n","orum, n. : les armes"),
array("aruum","aru","templum","n","i, n. : la terre, le champ, la plaine"),
array("aurum","aur","templum","n","i, n. : or"),
array("auxilium","auxili","templum","n","ii, n. : l'aide, le secours"),
array("bellum","bell","templum","n","i, n. : guerre"),
array("beneficium","benefici","templum","n","ii, n. : service, bienfait, faveur"),
array("bracchium","bracchi","templum","n","ii, n. : bras"),
array("caelum","cael","templum","n","i, n. : ciel"),
array("castellum","castell","templum","n","i, n. : redoute, fortin"),
//array("castra","cast","templum","n","orum, n. pl. : camp militaire"),
array("collum","coll","templum","n","i, n. : cou"),
array("consilium","consili","templum","n","ii, n. : délibération, conseil, assemblée, projet, plan"),
array("dictum","dict","templum","n","i, n. : la parole"),
array("donum","don","templum","n","i, n. : présent, cadeau"),
array("dubium","dubi","templum","n","ii, n. : doute"),
array("exemplum","exempl","templum","n","i, n. : exemple"),
array("exilium","exili","templum","n","ii, n. : exil"),
array("exsilium","exsili","templum","n","ii; n. : l'exil"),
array("factum","fact","templum","n","i, n. : le fait, l'action, le travail, l'ouvrage"),
array("fatum","fat","templum","n","i, n. : la prédiction, le destin, la fatalité, la destinée"),
array("ferrum","ferr","templum","n","i, n. : fer, outil ou arme de fer"),
array("forum","for","templum","n","i, n. : marché, forum"),
array("fretum","fret","templum","n","i, n. : le détroit, la mer, les flots"),
array("frumentum","frument","templum","n","i, n. : blé"),
array("gaudium","gaudi","templum","n","ii, n. : contentement, satisfaction, joie"),
array("impedimentum","impediment","templum","n","i, n. : obstacle ; au pl. : bagages"),
array("imperium","imperi","templum","n","ii, n. : pouvoir (absolu)"),
array("ingenium","ingeni","templum","n","ii, n. : qualités innées, caractère, esprit, intelligence"),
array("initium","initi","templum","n","ii, n. : début"),
array("interuallum","interuall","templum","n",", i, n. : l'intervalle, l'espace"),
array("iudicium","iudici","templum","n","ii, n. : jugement, décision"),
array("iugum","iug","templum","n","i, n. : joug, attelage, liens, cime, hauteur"),
array("malum","mal","templum","n","i, n. : pomme"),
array("membrum","membr","templum","n","i, n. (généralement au plur) : membre, organe"),
array("negotium","negoti","templum","n","ii, n. : affaire, mission"),
array("odium","odi","templum","n","i, n. : haine"),
array("officium","offici","templum","n","ii, n. : service, fonction, devoir, obligation morale"),
array("otium","oti","templum","n","ii, n. : le  loisir, le calme, le repos"),
array("pactum","pact","templum","n","i, n. : le pacte, la convention, la manière"),
array("periculum","pericul","templum","n","i, n. : essai, expérience, danger"),
array("pomum","pom","templum","n","i, n. : fruit"),
array("praeceptum","praecept","templum","n","i, n. : le précepte, la règle, la leçon"),
array("praemium","praemi","templum","n","ii, n. : récompense"),
array("praesidium","praesidi","templum","n","ii, n. : garde"),
array("pretium","preti","templum","n","ii, n. : le prix, la valeur, la récompense, le salaire"),
array("principium","principi","templum","n","ii, n. : commencement, origine"),
array("proelium","proeli","templum","n","ii, n. : combat"),
array("remedium","remedi","templum","n","i, n. : remède (+ gén : contre)"),
array("saeculum","saecul","templum","n","i, n. : époque, âge"),
array("saxum","sax","templum","n","pierre, rocher, roche"),
array("seruitium","seruiti","templum","n","i, n. : servitude, esclavage"),
array("signum","sign","templum","n","i, n. : le signe, l'enseigne, l'oeuvre d'art"),
array("solum","sol","templum","n","i, n. : le sol"),
array("spatium","spati","templum","n","ii, n. : la distance, l'espace (lieu ou temps)"),
array("studium","studi","templum","n","ii, n. : ardeur, affection, intérêt, passion, étude"),
array("supplicium","supplici","templum","n","i, n. : le supplice"),
array("tectum","tect","templum","n","i, n. : toit, maison"),
array("telum","tel","templum","n","i, n. : trait (javelot ou flèche)"),
array("templum","templ","templum","n","i, n. : temple"),
array("tergum","terg","templum","n","i, n. : dos"),
array("tormentum","torment","templum","n","i, n. : machine de guerre, torture"),
array("uallum","uall","templum","n","i, n. : palissade, retranchement"),
array("uelum","uel","templum","n","i, n. : la voile"),
array("uerbum","uerb","templum","n","i, n.  mot, parole"),
array("uestigium","uestigi","templum","n","ii, n. : trace de pas, trace"),
array("uinculum","uincul","templum","n","i, n. : lien, chaîne"),
array("uinum","uin","templum","n","i, n. : vin"),
array("uitium","uiti","templum","n","ii, n. : vice, défaut"),
array("uotum","uot","templum","n","i, n. : voeu, offrande"),
);
?>
