<?php
$bini = array(
array("agricola", "paysan" ),
array("amicitia", "amitié" ),
array("anima", "souffle, vie, souffle vital"),
array("aqua", "eau"),
array("ara", "autel"),
array("arena", "sable"),
array("audacia", "audace"),
array("auaritia", "avidité, cupidité, avarice"),
array("aura", "brise, vent léger"),
array("beneuolentia", "bienveillance"),
array("causa","cause, procès"),
array("cena","dîner, repas du soir"),
array("clementia","clémence"),
array("columna","colonne"),
array("coma","chevelure, cheveux"),
array("concordia","concorde, entente"),
array("copia","abondance ; pl. richesses, troupes"),
array("corona","couronne, badauds"),
array("culpa","faute"),
array("cura","soin, souci"),
array("dea","déesse"),
array("dextra","main droite"),
array("diligentia","empressement, zêle, soin scrupuleux"),
array("disciplina","enseignement"),
array("discordia","discorde"),
array("domina","maîtresse"),
array("eloquentia","éloquence"),
array("epistula","lettre"),
array("fabula","mythe, fable, pièce de théâtre, histoire"),
array("fama","nouvelle, rumeur, réputation"),
array("familia","famille, maisonnée"),
array("flamma","flamme"),
array("fera","bête sauvage"),
array("filia","fille, par rapport à ses parents"),
array("flamma","flamme"),
array("forma","forme, beauté"),
array("fortuna","fortune, chance"),
array("fuga","fuite"),
array("gloria","gloire"),
array("gratia","grâce, reconnaissance"),
array("herba","herbe"),
array("hora","heure"),
array("incola","habitant"),
array("industria","activité"),
array("iniuria","injustice, violation du droit"),
array("inopia","pauvreté, manque"),
array("insula","île, immeuble à appartements"),
array("inuidia","jalousie, envie, haine"),
array("ira","colère"),
array("iustitia","justice"),
array("lacrima","larme"),
array("laetitia","joie"),
array("licentia","liberté, pouvoir, licence"),
array("lingua","langue"),
array("littera","lettre de l'alphabet"),
array("luna","lune"),
array("materia","matière, sujet, prétexte"),
array("memoria","mémoire, souvenir"),
array("mensa","table"),
array("militia","service militaire"),
array("molestia","peine, chagrin, gêne"),
array("mora","délai, retard, obstacle"),
array("natura","nature"),
array("nauta","marin"),
array("opera","travail, peine, effort"),
array("ora","bord, limite, lisière, côte"),
array("patria","patrie"),
array("pecunia","argent"),
array("persona","masque, rôle, caractère"),
array("philosophia","philosophie"),
array("pirata","pirate"),
array("poena","châtiment"),
array("poeta","poète"),
array("porta","porte (d'une ville)"),
array("praeda","butin, dépouilles, proie"),
array("prouincia","province"),
array("prudentia","prévoyance, habileté, sagesse"),
array("puella","jeune fille"),
array("pugna","bataille, combat"),
array("regina","reine"),
//array("respublica","état, politique"),
array("ripa","rive"),
array("sapientia","sagesse, bon sens"),
array("saeuitia","cruauté"),
array("sententia","avis, opinion"),
array("silua","forêt"),
array("superbia","orgueil, arrogance"),
array("temperantia","modération, maîtrise de soi"),
array("terra","terre"),
array("turba","foule, désordre, trouble"),
array("uena","veine"),
array("uenia","pardon"),
array("uia","route, chemin, voyage"),
array("uictoria","victoire"),
array("uita","vie"),
array("umbra","ombre"),
array("unda","onde, eau, flot")
);
?>
