<?php
$bini = array(
   array("aditus","accès"),
   array("aduentus","arrivée, venue"),
   array("aestus","chaleur, bouillonnement, vagues, marée"),
   array("affectus","disposition de l'âme, sentiment"),
   array("casus","hasard, malheur, chute"),
   array("conspectus","vue, regard"),
   array("consulatus","consulat"),
   array("cornu","corne, aile d'une ligne de bataille. "),
   array("cultus","culture du sol, culture, éducation, culte, égards, moeurs, parure"),
   array("currus","char"),
   array("cursus","course, parcours, trajet"),
   array("domus","maison"),
   array("equitatus","cavalerie"),
   array("exercitus","armée"),
   array("exitus","sortie, issue, résultat, aboutissement, mort, fin, conclusion"),
   array("fructus","droit qu'on a sur qqch, usufruit, fruit, récompense, résultat"),
   array("genu","genou"),
   array("gradus","degré, échelon, rang"),
   array("habitus","manière d'être, apparence"),
   array("ictus","coup, choc"),
   array("impetus","mouvement en avant, élan, assaut"),
   array("magistratus","charge, magistrature, fonction publique"),
   array("manus","main, petite troupe"),
   array("metus","peur, crainte"),
   array("motus","mouvement, trouble, révolte, émotion, excitation, secousse"),
   array("paratus","préparation, apprêt, préparatif"),
   array("passus","pas (1, 479 m.)"),
   array("porticus","portique"),
   array("portus","port"),
   array("senatus","sénat"),
   array("sensus","sens, sentiments"),
   array("sinus","sein, courbure, golfe, anse"),
   array("spiritus","souffle, vie, inspiration"),
   array("uersus","sillon, ligne, vers"),
   array("usus","usage, utilité"),
   array("uultus","regard, visage"),
   array("acies","ligne de bataille; regard"),
   array("dies","jour"),
   array("facies","forme extérieure, apparence, figure"),
   array("fides","confiance, loyauté"), 
   array("res","chose, événement, circonstance, affaire judiciaire;  biens"),
   array("species","vision sans réalité, apparence, aspect, prétexte"),
   array("spes","espoir")
   );
?>   
