<?php
$bini = array(
   //array("adulescens","jeune homme"),
   array("aedes","maison, temple"),
   array("aequor","surface plane, poét. mer"),
   array("aer","air"),
   array("aes","cuivre, bronze ; - alienum : dette"),
   array("aetas","partie de la vie, âge, époque"),
   array("agmen","armée en marche, colonne de marche"),
   array("altitudo","altitude, hauteur"),
   array("amnis","fleuve, rivière. - commence par la lettre a"),
   array("amor","amour"),
   array("animal","être vivant, animal"),
   array("apis","abeille"),
   array("arbor","arbre"),
   array("ardor","feu, embrasement, ardeur, passion"),
   array("ars","habileté, métier, profession, art"),
   array("arx","citadelle"),
   array("auctor","garant, modèle, auteur"),
   array("auctoritas","avis, prestige, autorité, volonté (du Sénat)"),
   array("auis","oiseau"),
   array("auris","oreille"),
   array("beatitudo", "bonheur. finit en -o"),
   array("bos","boeuf"),
   array("caedes","meurtre, massacre"),
   array("canis","chien"),
   array("caput","tête, capitale"),
   array("carmen","poème, incantation"),
   array("centurio","centurion"),
   array("certamen","combat, lutte, conflit"),
   array("ceruix","nuque, encolure"),
   array("ciuis","citoyen"),
   array("ciuitas","cité, état"),
   array("clamor","clameur, cri"),
   array("classis","classe, flotte"),
   array("cohors","cohorte"),
   array("collis","colline"),
   array("color","couleur, teint du visage, éclat (du style)"),
   array("comes","compagnon"),
   array("condicio","condition"),
   array("coniux","épouse, époux"),
   array("consuetudo","habitude, coutume, usage - commence par c."),
   array("consul","consul"),
   array("corpus","corps"),
   array("crassitudo","épaisseur, grosseur"),
   array("crimen","accusation, chef d'accusation"),
   array("cubile","lit, couche"),
   array("cupido","désir. finit en -o"),
   array("cupiditas","désir. finit en -itas"),
   array("custos","gardien"),
   array("decus","gloire, honneur. commence en d-"),
   array("dens","dent"),
   array("difficultas","difficulté"),
   array("dignitas","dignité, considération, rang"),
   array("discrimen","différence, ligne de démarcation, position critique"),
   array("dolor","douleur"),
   array("dux","chef, guide"),
   array("eques","chevalier, cavalier"),
   array("error","action de s'égarer, erreur"),
   array("facinus","action, acte, forfait,  crime"),
   array("fax","torche"),
   array("felicitas","bonheur. finit en -as"),
   array("fides","lyre. Toujours au pluriel"),
   array("finis","limite, fin ; pl., frontière, territoire"),
   array("flumen","cours d'eau, fleuve, rivière - commence par la lettre f"),
   array("fons","source, fontaine, cause, principe"),
   array("frater","frère"),
   array("fraus","mauvaise foi, tromperie"),
   array("frigus","froid, froidure"),
   array("frons","feuillage"),
   array("fulmen","foudre"),
   array("funus","funérailles, ensevelissement ; mort, ruine"),
   array("gens","famille, nation"),
   array("genus","race, origine, espèce"),
   array("gladiator","gladiateur"),
   array("grauitas","pesanteur, sévérité, dignité, majesté, malaise"),
   array("grex","troupeau"),
   array("hiems","hiver"),
   array("homo","homme, humain"),
   //array("honor","honneur, hommage, la charge, la magistrature, honoraires"),
   array("honos","honneur, hommage, charge, magistrature, honoraires. finit en -s"),
   array("hostis","ennemi"),
   array("humor","eau, liquide. Finit en -mor"),
   array("ignis","feu"),
   array("imago","imitation, image"),
   array("imber","pluie"),
   array("imperator","général en chef"),
   array("infans","bébé"),
   array("intentio","application, effort, volonté"),
   array("iter","chemin, voyage"),
   array("iudex","juge"),
   array("ius","serment, droit"),
   array("iuuenis","jeune homme/fille, citoyen en âge de porter les armes"),
   array("iuuentus","jeunesse"),
   array("lapis","pierre"),
   array("latitudo","largeur"),
   array("latus","côté"),
   array("laus","louange, gloire, honneur"),
   array("legio","légion"),
   array("lex","loi, condition(s) d'un traité"),
   array("libertas","liberté"),
   array("libido","désir, envie, débauche"),
   array("limen","seuil, entrée"),
   array("litus","rivage"),
   array("lumen","lumière, flambeau, pl. les yeux"),
   array("lux","lumière, jour"),
   array("magnitudo","grande taille"),
   array("maiores","ancêtres"),
   array("mare","mer"),
   array("mater","mère"),
   array("mens","esprit"),
   array("miles","soldat"),
   array("moenia","murs, murailles, remparts"),
   array("moles","masse, poids, charge"),
   array("mons","montagne"),
   array("mors","mort"),
   array("mos","usage, habitude ; pl. moeurs -commence par m- "),
   array("multitudo","foule, grand nombre"),
   array("munitio","terrassement, fortification"),
   array("munus","obligation, charge, spectacle public"),
   array("natio","nation, nationalité"),
   array("nauis","navire"),
   array("necessitas","nécessité"),
   array("nemus","forêt, bois"),
   array("nomen","nom"),
   array("nox","nuit"),
   array("nubes","nuage, nue, nuée"),
   array("numen","volonté des dieux, puissance divine; divinité"),
   array("onus","fardeau"),
   array("opinio","opinion, préjugé"),
   array("ops","sing., pouvoir, aide ; pl., richesses"),
   array("opus","travail (- est mihi = j'ai besoin)"),
   array("oratio","langage, parole, exposé, discours"),
   array("orbis","globe, monde"),
   array("ordo","ordre, disposition"),
   array("os","os"),
   array("parens","parent"),
   array("paries","paroi, mur"),
   array("pars","partie, côté"),
   array("pater","père ; pl. sénateurs"),
   array("paupertas","pauvreté"),
   array("pax","paix"),
   array("pectus","poitrine, coeur, intelligence"),
   array("pecus","bétail"),
   array("pedes","fantassin, piéton"),
   array("pes","pied"),
   array("pietas","respect, patriotisme, piété, affection"),
   array("piscis","poisson"),
   array("plebs","plèbe"),
   array("pondus","poids"),
   array("pons","pont"),
   array("potestas","puissance, pouvoir, pouvoir d'un magistrat, occasion de faire qqch. "),
   array("praetor","préteur"),
   array("pudor","honte, réserve, timidité. Finit en -or"),
   array("puluis","poussière"),
   array("quies","repos, calme, tranquilité"),
   array("ratio","raison, raisonnement, compte"),
   array("ratis","radeau, navire"),
   array("regio","région, quartier"),
   array("rex","roi"),
   array("robur","rouvre, chêne, dureté, solidité"),
   array("sanguis","sang, vigueur"),
   array("scelus","crime"),
   array("sedes","siège, place"),
   array("semen","graine, semence"),
   array("senectus","vieillesse"),
   array("senex","vieillard"),
   array("sermo","conversation, dialogue, discussion, discours, langue"),
   array("sol","soleil"),
   array("soror","soeur"),
   array("tellus","terre, sol, terrain, pays"),
   array("tempestas","temps, mauvais temps"),
   array("tempus","temps"),
   array("terror","terreur, effroi, épouvante. Ce n'est pas pauor."),
   array("testis","témoin"),
   array("timor","peur"),
   array("turris","tour"),
   array("uates","devin, poète"),
   array("uer","printemps"),
   array("uestis","vêtement"),
   array("uictor","vainqueur"),
   array("uirgo","vierge, jeune fille non mariée"),
   array("uirtus","courage, honnêteté"),
   array("uis","force"),
   //array("umor","eau, liquide"),
   array("uoluntas","volonté"),
   array("uoluptas","volupté"),
   array("uox","voix, son de la voix, parole, mot"),
   array("urbs","ville"),
   array("utilitas","utilité"),
   array("uulnus","blessure"),
   array("uxor","épouse, femme")
);
?>
