<?php
$bini = array(
array("amicus","ami"),
array("animus","coeur, fierté, courage, esprit"),
array("annus","année"),
array("campus","plaine, champ"),
array("cibus","nourriture"),
array("deus","dieu"),
array("digitus","doigt"),
array("dolus","ruse, adresse"),
array("dominus","maître, seigneur"),
array("equus","cheval"),
array("filius","fils"),
array("gladius","glaive"),
array("humerus","épaule"),
array("humus","sol, terre"),
array("lacertus","bras ; pl. muscles"),
array("lectus","lit"),
array("legatus","ambassadeur, envoyé, légat"),
array("locus","lieu, endroit - le pluriel est neutre -"),
array("lucus","bois sacré"),
array("maritus","mari"),
array("modus","mesure, limite, manière"),
array("morbus","maladie"),
array("mundus","univers, monde"),
array("murus","mur"),
array("necessarius","ami intime, familier"),
array("neruus","nerf"),
array("numerus","nombre"),
array("oculus","oeil"),
array("oppidum","place forte, ville"),
array("philosophus","philosophe"),
//array("pontus","haute mer, mer"),
array("populus","peuple"),
array("praefectus","gouverneur, administrateur"),
array("reus","accusé"),
array("seruus","esclave"),
//array("sestertius","ii, m. sesterce"),
array("somnus","sommeil"),
array("taurus","taureau"),
array("torus","renflement, muscle saillant ; lit"),
array("tribunus","tribun"),
array("uentus","vent"),
//array("umerus","épaule"),
array("uulgus","foule, le commun des hommes"),
array("aedificium","édifice"),
array("aeuum","époque, durée, âge"),
array("argumentum","argument, preuve, matière, sujet"),
//array("arma","orum, n. : les armes"),
array("aruum","terre labourée"),
array("aurum","or"),
array("auxilium","aide, secours"),
array("bellum","guerre"),
array("beneficium","bienfait, faveur"),
//array("bracchium","bras"),
array("caelum","ciel, climat"),
array("castellum","redoute, fortin"),
//array("castra","orum, n. pl. : camp militaire"),
array("collum","cou"),
array("consilium","délibération, décision, conseil, plan"),
array("dictum","chose dite, promesse, proverbe"),
array("donum","présent, cadeau"),
array("dubium","doute"),
array("exemplum","exemple"),
array("exilium","exil"),
array("exsilium","exil"),
array("factum","fait, action, travail, ouvrage"),
array("fatum","prédiction, destin, fatalité, destinée"),
array("ferrum","fer, outil ou arme de fer"),
array("forum","marché, forum"),
array("fretum","détroit, mer, flots"),
array("frumentum","blé"),
array("gaudium","contentement, satisfaction, joie"),
array("impedimentum","obstacle ; au pl. : bagages"),
array("imperium","pouvoir absolu"),
array("ingenium","qualités innées, caractère, esprit, intelligence"),
array("initium","début, commencement"),
array("interuallum", "intervalle, distance"),
array("iudicium","jugement, décision"),
array("iugum","joug, attelage, chaîne de montagnes, cime, hauteur"),
array("malum","pomme"),
array("membrum","i, n. (généralement au plur) : membre, organe"),
array("negotium","occupation, travail, affaire"),
array("odium","haine"),
array("officium","fonction, devoir, obligation morale"),
array("otium","loisir, calme, repos"),
array("pactum","pacte, convention, manière"),
array("periculum","danger, essai, expérience"),
array("pomum","fruit"),
array("praeceptum","précepte, règle, leçon"),
array("praemium","récompense"),
array("praesidium","garde, garnison, protection"),
array("pretium","prix, valeur, récompense, salaire"),
array("principium","commencement, origine"),
array("proelium","combat"),
array("remedium","remède (+ gén : contre)"),
array("saeculum","génération, époque, siècle"),
array("saxum","pierre, rocher, roche"),
array("seruitium","servitude, esclavage"),
array("signum","signe, enseigne, oeuvre d'art"),
array("spatium","vaste étendue, espace (lieu ou temps)"),
array("studium","ardeur, affection, intérêt, passion, étude"),
array("supplicium","supplice"),
array("tectum","toit, maison"),
array("telum","trait (javelot ou flèche)"),
array("templum","temple"),
array("tergum","dos"),
array("tormentum","(intrument de) torture"),
array("uallum","palissade, retranchement"),
array("uelum","voile"),
array("uerbum","mot, parole"),
array("uestigium","trace de pas, trace"),
array("uinculum","lien, chaîne"),
array("uinum","vin"),
array("uitium","vice, défaut"),
array("uotum","voeu, offrande"),
);
?>
