<?php
$lex = array(
array("amicitia","amiciti","uita","f","ae, f. : amitié"),
array("anima","anim","uita","f","ae, f. : coeur, âme"),
array("aqua","aqu","uita","f","ae, f. : eau"),
array("ara","ar","uita","f","ae, f. : autel"),
array("arena","aren","uita","f","ae, f. : sable"),
array("auaritia","auariti","uita","f","ae, f. : cupidité, avarice"),
array("aura","aur","uita","f","ae, f. : le souffle, la brise, le vent, l'air"),
array("causa","caus","uita","n","ae, f. : cause, motif; affaire judiciaire, procès"),
array("columna","column","uita","f","ae, f. : colonne"),
array("coma","com","uita","f","ae, f. : chevelure, cheveux"),
array("copia","copi","uita","f","ae, f. : abondance, possibilité ; pl. les richesses, les troupes"),
array("corona","coron","uita","f","ae, f. : la couronne, les badauds"),
array("culpa","culp","uita","f","ae, f. : la faute"),
array("cura","cur","uita","f","ae, f. : soin, souci"),
array("dea","de","uita","f","ae, f. : déesse"),
array("dextra","dextr","uita","f","ae, f. : la main droite"),
array("domina","domin","uita","f","ae, f. : la maîtresse"),
array("fabula","fabul","uita","f","ae, f. : mythe, fable, pièce (de théâtre), histoire"),
array("fama","fam","uita","f","ae, f. : la nouvelle, la rumeur, la réputation"),
array("familia","famili","uita","f","ae, f. : famille, maisonnée"),
array("femina","femin","uita","f","ae, f. : femme"),
array("fera","fer","uita","f","ae, f. : la bête sauvage"),
array("filia","fili","uita","f","ae, f. : fille"),
array("flamma","flamm","uita","f","ae, f. : flamme"),
array("forma","form","uita","f","ae, f. : forme, beauté"),
array("fortuna","fortun","uita","f","ae, f. : fortune, chance"),
array("fuga","fug","uita","f","ae, f. : la fuite"),
array("gloria","glori","uita","f","ae, f. : gloire"),
array("gratia","grati","uita","f","ae, f. : grâce, reconnaissance"),
array("herba","herb","uita","f","ae, f. : herbe"),
array("hora","hor","uita","f","ae, f. : heure"),
array("iniuria","iniuri","uita","f","ae, f. : injustice, violation du droit"),
array("inopia","inopi","uita","f","ae, f. : pauvreté, manque"),
array("insula","insul","uita","f","ae, f. : l'île, l'immeuble à appartements"),
array("inuidia","inuidi","uita","f","ae, f. : jalousie, envie, haine"),
array("ira","ir","uita","f","ae, f. : colère"),
array("iuuenta","iuuent","uita","f","ae, f. : la jeunesse"),
array("lacrima","lacrim","uita","f","ae, f. : larme"),
array("lingua","lingu","uita","f","ae, f. : langue"),
array("littera","litter","uita","f","ae, f. : lettre"),
array("luna","lun","uita","f","ae, f. : lune"),
array("materia","materi","uita","f","ae, f. : matière, sujet, prétexte"),
array("memoria","memori","uita","f","ae, f. : mémoire, souvenir"),
array("mensa","mens","uita","f","ae, f. : table"),
array("mora","mor","uita","f","ae, f. : délai, retard, obstacle"),
array("natura","natur","uita","f","ae, f. : nature"),
array("opera","oper","uita","f","ae, f. : le soin, l'effort (operam dare : se consacrer à)"),
array("ora","or","uita","f","ae, f. : bord, limite, lisière, côte"),
array("patria","patri","uita","f","ae, f. : patrie"),
array("pecunia","pecuni","uita","f","ae, f. : argent"),
array("persona","person","uita","f","ae, f. : le masque, le rôle, le caractère"),
array("philosophia","philosophi","uita","f","ae, f. : philosophie"),
array("poena","poen","uita","f","ae, f. : le châtiment (dare poenas : subir un châtiment)"),
array("porta","port","uita","f","ae, f. : porte (d'une ville)"),
array("potentia","potenti","uita","f","ae, f. : force, puissance"),
array("praeda","praed","uita","f","ae, f. : le  butin, les dépouilles, la proie"),
array("prouincia","prouinci","uita","f","ae, f. : la province"),
array("prudentia","prudenti","uita","f","ae, f. : la prévoyance, la prévision"),
array("puella","puell","uita","f","ae, f. : fille, jeune fille"),
array("pugna","pugn","uita","f","ae, f. : la bataille, le combat, le pugilat"),
array("regina","regin","uita","f","ae, f. : reine"),
//array("respublica","respublic","uita","","reipublicae : l'état, la politique"),
array("ripa","rip","uita","f","ae, f. : rive"),
array("sapientia","sapienti","uita","f","ae, f. : sagesse"),
array("sententia","sententi","uita","f","ae, f. : avis, opinion"),
array("silua","silu","uita","f","ae, f. : forêt"),
array("summa","summ","uita","f","ae, f. : l'ensemble"),
array("terra","terr","uita","f","ae, f. : terre"),
array("turba","turb","uita","f","ae, f. : foule, désordre, émoi"),
array("uena","uen","uita","f","ae, f. : la veine"),
array("uia","ui","uita","f","ae, f. : route, chemin, voyage"),
array("uictoria","uictori","uita","f","ae, f. : victoire"),
array("uita","uit","uita","f","ae, f. : vie"),
array("umbra","umbr","uita","f","ae, f. : ombre"),
array("unda","und","uita","f","ae, f. : l'onde, l'eau, le flot")
);
?>
