<?php
$bini = array(
   //array("adulescens","","","jeune homme"),
   array("aedes","aedis","f","maison, temple"),
   array("aequor","aequoris","n","surface plane, poét. mer"),
   array("aer","aeris","n","air"),
   array("aes","aeris","n","cuivre, bronze ; - alienum : dette"),
   array("aetas","aetatis","f","partie de la vie, âge, époque"),
   array("agmen","agminis","n","armée en marche, colonne de marche"),
   array("altitudo","altitudinis","f","altitude, hauteur"),
   array("amnis","amnis","m","fleuve, rivière. - commence par la lettre a"),
   array("amor","amoris","m","amour"),
   array("animal","animalis","n","être vivant, animal"),
   array("apis","apis","f","abeille"),
   array("arbor","arboris","f","arbre"),
   array("ardor","ardoris","m","feu, embrasement, ardeur, passion"),
   array("ars","artis","f","habileté, métier, profession, art"),
   array("arx","arcis","f","citadelle"),
   array("auctor","auctoris","m","garant, modèle, auteur"),
   array("auctoritas","auctoritatis","f","avis, prestige, autorité, volonté (du Sénat)"),
   array("auis","auis","m","oiseau"),
   array("auris","auris","f","oreille"),
   array("beatitudo","beatitudinis","f","bonheur. finit en -o"),
   array("bos","bouis","m","boeuf"),
   array("caedes","caedis","f","meurtre, massacre"),
   array("canis","canis","mf","chien"),
   array("caput","capitis","n","tête, capitale"),
   array("carmen","carminis","n","poème, incantation"),
   array("centurio","centurionis","m","centurion"),
   array("certamen","certaminis","n","combat, lutte, conflit"),
   array("ceruix","ceruicis","f","nuque, encolure"),
   array("ciuis","ciuis","m","citoyen"),
   array("ciuitas","ciuitatis","f","cité, état"),
   array("clamor","clamoris","m","clameur, cri"),
   array("classis","classis","f","classe, flotte"),
   array("cohors","cohortis","f","cohorte"),
   array("collis","collis","m","colline"),
   array("color","coloris","m","couleur, teint du visage, éclat (du style)"),
   array("comes","comitis","m","compagnon"),
   array("condicio","condicionis","f","condition"),
   array("coniux","coniugis","mf","épouse, époux"),
   array("consuetudo","consuetudinis","f","habitude, coutume, usage - commence par c."),
   array("consul","consulis","m","consul"),
   array("corpus","corporis","n","corps"),
   array("crassitudo","crassitudinis","f","épaisseur, grosseur"),
   array("crimen","criminis","n","accusation, chef d'accusation"),
   array("cubile","cubilis","n","lit, couche"),
   array("cupido","cupidinis","m","désir. finit en -o"),
   array("cupiditas","cupiditatis","f","désir. finit en -itas"),
   array("custos","custodis","m","gardien"),
   array("decus","decoris","n","gloire, honneur. commence en d-"),
   array("dens","dentis","f","dent"),
   array("difficultas","difficultatis","f","difficulté"),
   array("dignitas","dignitatis","f","dignité, considération, rang"),
   array("discrimen","discriminis","n","différence, ligne de démarcation, position critique"),
   array("dolor","doloris","m","douleur"),
   array("dux","ducis","m","chef, guide"),
   array("eques","equitis","m","chevalier, cavalier"),
   array("error","erroris","m","action de s'égarer, erreur"),
   array("facinus","facinoris","n","action, acte, forfait,  crime"),
   array("fax","facis","f","torche"),
   array("felicitas","felicitatis","f","bonheur. finit en -as"),
   array("fides","fidium","f","lyre. Toujours au pluriel"),
   array("finis","finis","f","limite, fin ; pl., frontière, territoire"),
   array("flumen","fluminis","n","cours d'eau, fleuve, rivière - commence par la lettre f"),
   array("fons","fontis","f","source, fontaine, cause, principe"),
   array("frater","fratris","m","frère"),
   array("fraus","fraudis","f","mauvaise foi, tromperie"),
   array("frigus","frigoris","n","froid, froidure"),
   array("frons","frondis","f","feuillage"),
   array("fulmen","fulminis","n","foudre"),
   array("funus","funeris","n","funérailles, ensevelissement ; mort, ruine"),
   array("gens","gentis","f","famille, nation"),
   array("genus","generis","n","race, origine, espèce"),
   array("gladiator","gladiatoris","m","gladiateur"),
   array("grauitas","grauitatis","f","pesanteur, sévérité, dignité, majesté, malaise"),
   array("grex","gregis","m","troupeau"),
   array("hiems","hiemis","m","hiver"),
   array("homo","hominis","m","homme, humain"),
   //array("honor","","","honneur, hommage, la charge, la magistrature, honoraires"),
   array("honos","honoris","m","honneur, hommage, charge, magistrature, honoraires. finit en -s"),
   array("hostis","hostis","m","ennemi"),
   array("humor","humoris","m","eau, liquide. Finit en -mor"),
   array("ignis","iginis","m","feu"),
   array("imago","imaginis","f","imitation, image"),
   array("imber","imbris","m","pluie"),
   array("imperator","imperatoris","m","général en chef"),
   array("infans","infantis","m","bébé"),
   array("intentio","intentionis","f","application, effort, volonté"),
   array("iter","itineris","n","chemin, voyage"),
   array("iudex","iudicis","m","juge"),
   array("ius","iuris","n","serment, droit"),
   array("iuuenis","iuuenis","mf","jeune homme/fille, citoyen en âge de porter les armes"),
   array("iuuentus","iuuentutis","f","jeunesse"),
   array("lapis","lapidis","m","pierre"),
   array("latitudo","latitudinis","f","largeur"),
   array("latus","lateris","n","côté"),
   array("laus","laudis","f","louange, gloire, honneur"),
   array("legio","legionis","f","légion"),
   array("lex","legis","f","loi, condition(s) d'un traité"),
   array("libertas","libertatis","f","liberté"),
   array("libido","libidinis","f","désir, envie, débauche"),
   array("limen","liminis","n","seuil, entrée"),
   array("litus","litoris","n","rivage"),
   array("lumen","luminis","n","lumière, flambeau, pl. les yeux"),
   array("lux","lucis","f","lumière, jour"),
   array("magnitudo","magnitudinis","f","grande taille"),
   array("maiores","maiorum","m","ancêtres"),
   array("mare","maris","n","mer"),
   array("mater","matris","f","mère"),
   array("mens","mentis","f","esprit"),
   array("miles","militis","m","soldat"),
   array("moenia","moenium","n","murs, murailles, remparts"),
   array("moles","molis","f","masse, poids, charge"),
   array("mons","montis","m","montagne"),
   array("mors","mortis","f","mort"),
   array("mos","moris","m","usage, habitude ; pl. moeurs -commence par m- "),
   array("multitudo","multitudinis","f","foule, grand nombre"),
   array("munitio","munitionis","f","terrassement, fortification"),
   array("munus","muneris","n","obligation, charge, spectacle public"),
   array("natio","nationis","f","nation, nationalité"),
   array("nauis","nauis","f","navire"),
   array("necessitas","necessitatis","f","nécessité"),
   array("nemus","nemoris","n","forêt, bois"),
   array("nomen","nominis","n","nom"),
   array("nox","noctis","f","nuit"),
   array("nubes","nubis","f","nuage, nue, nuée"),
   array("numen","numinis","n","volonté des dieux, puissance divine; divinité"),
   array("onus","oneris","n","fardeau"),
   array("opinio","opinionis","f","opinion, préjugé"),
   array("ops","opis","f","sing., pouvoir, aide ; pl., richesses"),
   array("opus","operis","n","travail (- est mihi = j'ai besoin)"),
   array("oratio","orationis","f","langage, parole, exposé, discours"),
   array("orbis","orbis","m","globe, monde"),
   array("ordo","ordinis","m","ordre, disposition"),
   array("os","ossis","n","os"),
   array("os","oris","n","visage, bouche"),
   array("parens","parentis","m","parent"),
   array("paries","parietis","m","paroi, mur"),
   array("pars","partis","f","partie, côté"),
   array("pater","patris","m","père ; pl. sénateurs"),
   array("paupertas","paupertatis","f","pauvreté"),
   array("pax","pacis","f","paix"),
   array("pectus","pectoris","n","poitrine, coeur, intelligence"),
   array("pecus","pecoris","n","bétail"),
   array("pedes","peditis","m","fantassin, piéton"),
   array("pes","pedis","m","pied"),
   array("pietas","pietatis","f","respect, patriotisme, piété, affection"),
   array("piscis","piscis","m","poisson"),
   array("plebs","plebis","f","plèbe"),
   array("pondus","ponderis","n","poids"),
   array("pons","pontis","m","pont"),
   array("potestas","potestatis","f","puissance, pouvoir, pouvoir d'un magistrat, occasion de faire qqch. "),
   array("praetor","praetoris","m","préteur"),
   array("pudor","pudoris","m","honte, réserve, timidité. Finit en -or"),
   array("puluis","puluis","m","poussière"),
   array("quies","quietis","f","repos, calme, tranquilité"),
   array("ratio","rationis","f","raison, raisonnement, compte"),
   array("ratis","ratis","f","radeau, navire"),
   array("regio","regionis","f","région, quartier"),
   array("rex","regis","m","roi"),
   array("robur","roboris","n","rouvre, chêne, dureté, solidité"),
   array("sanguis","sanguis","m","sang, vigueur"),
   array("scelus","sceleris","n","crime"),
   array("sedes","sedis","f","siège, place"),
   array("semen","seminis","n","graine, semence"),
   array("senectus","senectutis","f","vieillesse"),
   array("senex","senis","f","vieillard"),
   array("sermo","sermonis","m","conversation, dialogue, discussion, discours, langue"),
   array("sol","solis","m","soleil"),
   array("soror","sororis","f","soeur"),
   array("tellus","telluris","f","terre, sol, terrain, pays"),
   array("tempestas","tempestatis","f","temps, mauvais temps"),
   array("tempus","temporis","n","temps"),
   array("terror","terroris","m","terreur, effroi, épouvante. Ce n'est pas pauor."),
   array("testis","testis","m","témoin"),
   array("timor","timoris","m","peur"),
   array("turris","turris","f","tour"),
   array("uates","uatis","m","devin, poète"),
   array("uer","ueris","n","printemps"),
   array("uestis","uestis","f","vêtement"),
   array("uictor","uictoris","m","vainqueur"),
   array("uirgo","uirginis","f","vierge, jeune fille non mariée"),
   array("uirtus","uirtutis","f","courage, honnêteté"),
   array("uis","nihil","f","force"),
   //array("umor","","","eau, liquide"),
   array("uoluntas","uoluntatis","f","volonté"),
   array("uoluptas","uoluptatis","f","volupté"),
   array("uox","uocis","f","voix, son de la voix, parole, mot"),
   array("urbs","urbis","f","ville"),
   array("utilitas","utilitatis","f","utilité"),
   array("uulnus","uulneris","n","blessure"),
   array("uxor","uxoris","f","épouse, femme")
);
?>
