<?php
$titre="Les verbes qu'il faut connaître en fin de quatrième";
$bini=array(
    array("abeo","eo","abiui,abii","abitum","s'éloigner, partir. Première lettre : a"),
    array("adeo","invaria","adii","aditum","aller dans, aller vers, aborder"),
    array("ago","lego","egi","actum","pousser devant soi, faire, traiter, agir"),
    array("amo","amo","amaui","amatum","aimer, être amoureux"),
    array("audio","audio","audiui","auditum","entendre (dire), écouter, apprendre"),
    array("capio","capio","cepi","captum","prendre. Première lettre : c"),
    array("cedo","lego","cessi","cessum","s'éloigner, être inférieur, céder à"),
    array("certo","amo","certaui","certatum","combattre, concourir. Premières lettres : ce"),
    array("cogito","amo","cogitaui","cogitatum","penser, réfléchir"),
    array("colo","lego","colui","cultum","honorer, cultiver, habiter"),
    array("condo","lego","condidi","conditum"," fonder une ville. Première lettre : c"),
    array("credo","lego","credidi","creditum","confier en prêt, croire, avoir confiance"),
    array("curo","amo","curaui","curatum","se charger de, prendre soin de, soigner"),
    array("dico","lego","dixi","dictum","dire"),
    array("do","amo","dedi","datum","donner"),
    array("eo","eo","ii,iui","itum","aller"),
    array("facio","capio","feci","factum","faire"),
    array("fugio","capio","fugi","-","s'enfuir, fuir"),
    array("gero","lego","gessi","gestum","porter, exécuter, faire. Première lettre : g"),
    array("habeo","moneo","habui","habitum","avoir, considérer comme"),
    array("inquit","invaria","-","-","dit-il, dit-elle"),
    array("iubeo","moneo","iussi","iussum","ordonner"),
    array("laudo","amo","laudaui","laudatum","louer, approuver"),
    array("lego","lego","legi","lectum","lire"),
    array("metuo","lego","metui","metutum","craindre. Première lettre : m"),
    array("mitto","lego","misi","missum","envoyer"),
    array("moueo","moneo","moui","motum","déplacer, émouvoir"),
    array("oro","amo","oraui","oratum","prier. Première lettre : o"),
    array("peruenio","audio","perueni","peruentum","parvenir"),
    array("peto","lego","peti,petiui","petitum","chercher à atteindre, attaquer, demander"),
    array("pono","lego","posui","positum","poser, placer"),
    array("possum","sum","potui","-","pouvoir"),
    array("pugno","amo","pugnaui","pugnatum","combattre. Première lettre : p"),
    array("puto","amo","putaui","putatum","penser, supposer"),
    array("rapio","capio","rapui","raptum","ravir, se saisir vivement de"),
    array("rogo","amo","rogaui","rogatum"," demander. Première lettre : r"),
    array("seruo","amo","seruaui","seruatum","veiller sur, sauver"),
    array("sum","sum","fui","-","être"),
    array("teneo","moneo","tenui","tentum","tenir, retenir, empêcher"),
    array("uenio","audio","ueni","uentum","venir"),
    array("uideo","moneo","uidi","uisum","voir. Au passif : paraître, sembler"),
    array("uinco","lego","uici","uictum","vaincre"),
    array("uoco","amo","uocaui","uocatum","appeler"),
    array("uolo","lego","uolui","-","vouloir"),
    array("absum","sum","afui","-","être absent"),
    array("accipio","capio","accepi","acceptum","accueillir, recevoir"),
    array("adsum","sum","adfui","-","être présent, assister, aider"),
    array("amitto","lego","amisi","amissum","perdre. Première lettre : a"),
    array("aspicio","capio","aspexi","aspectum","regarder, examiner, considérer, voir. Première lettre : a"),
    array("audeo","moneo","ausus sum","-","oser"),
    array("cado","lego","cecidi","casum","tomber"),
    array("cano","lego","cecini","cantum","chanter, jouer d'un instrument de musique"),
    array("careo","moneo","carui","-","manquer de, être privé de. Première lettre : c"),
    array("caueo","moneo","caui","cautum","être sur ses gardes, éviter. Première lettre : c"),
    array("claudo","lego","clausi","clausum","enfermer, fermer"),
    array("cognosco","lego","cognoui","cognitum","apprendre à connaître"),
    array("cogo","lego","coegi","coactum","rassembler, pousser de force, forcer"),
    array("conficio","capio","confeci","confectum","faire intégralement, accabler. Première lettre : c"),
    array("contemno","lego","contempsi","contemptum","mépriser, dédaigner, ne pas craindre."),
    array("cupio","capio","cupi, cupiui","cupitum","désirer"),
    array("curro","lego","cucurri","cursum","courir"),
    array("debeo","moneo","debui","debitum","devoir"),
    array("decerno","lego","decreui","decretum","décréter, décider"),
    array("delecto","amo","delectaui","delectatum","charmer, faire plaisir à"),
    array("desidero","amo","desideraui","desideratum","avoir besoin de ; manquer de. (4 syllabes)"),
    array("desum","sum","defui","-"," manquer. première lettre : d"),
    array("diligo","lego","dilexi","dilectum","aimer. Première lettre : d"),
    array("disco","lego","didici","discitum","apprendre (une leçon, une nouvelle). s'instruire, étudier."),
    array("doceo","moneo","docui","doctum","enseigner (+ 2 acc.)"),
    array("doleo","moneo","dolui","dolitum","souffrir, être affligé"),
    array("duco","lego","duxi","ductum","conduire, emmener, épouser, estimer. Première lettre : d"),
    array("egeo","moneo","egui","-","manquer de. Première lettre : e"),
    array("emo","lego","emi","emptum","acheter"),
    array("eripio","capio","eripui","ereptum","tirer brusquement hors de, arracher"),
    array("excipio","capio","excepi","exceptum","retirer de, excepter, accueillir"),
    array("existimo","amo","existimaui","existimatum","estimer, juger, être d'avis. Première lettre : e"),
    array("faueo","moneo","faui","fautum","être favorable à, s'intéresser à"),
    array("fero","lego","tuli","latum","porter, supporter"),
    array("fingo","lego","finxi","fictum","façonner, imaginer, feindre"),
    array("fio","audio","factus sum","-","devenir, arriver; sert de passif à facio"),
    array("fleo","moneo","fleui","fletum","pleurer"),
    array("frango","lego","fregi","fractum","briser. Première lettre : f"),
    array("gaudeo","moneo","gauisus sum","-","se réjouir. Première lettre : g"),
    array("impero","amo","imperaui","imperatum","commander"),
    array("incipio","capio","incepi","inceptum","commencer"),
    array("inuideo","moneo","inuidi","inuisum"," être jaloux, envier"),
    array("iaceo","moneo","iacui","-","être étendu, s'étendre"),
    array("iudico","amo","iudicaui","iudicatum","juger, faire office de juge"),
    array("iungo","lego","iunxi","iunctum","joindre"),
    array("iuuo","amo","iuui","iutum","être utile, aider, secourir. Première lettre : i"),
    array("laboro","amo","laboraui","laboratum","peiner, travailler, souffrir"),
    array("licet","pronoms","licui","licitum","il est permis"),
    array("ludo","lego","lusi","lusum","jouer"),
    array("maneo","moneo","mansi","mansum","rester"),
    array("moneo","moneo","monui","monitum","avertir, engager à"),
    array("narro","amo","narraui","narratum","conter, raconter"),
    array("nego","amo","negaui","negatum","nier"),
    array("nescio","audio","nesciui","nescitum","ignorer. Première lettre : n"),
    array("nolo","lego","nolui","-","ne pas vouloir, refuser"),
    array("nosco","lego","noui","notum","apprendre ; pf. savoir"),
    array("occido","lego","occidi","occasum","tomber, périr, se coucher (soleil)"),
    array("occupo","amo","occupaui","occupatum","occuper, envahir, remplir, devancer, couper (la parole)"),
    array("odi","lego","odi","-"," haïr (toujours au parfait)"),
    array("oportet","lego","oportuit","-","il importe, il faut"),
    array("opto","amo","optaui","optatum","souhaiter"),
    array("ostendo","lego","ostendi","ostentum","tendre, montrer"),
    array("parco","lego","peperci","parsum","épargner, faire grâce à"),
    array("pareo","moneo","parui","paritum","paraître, apparaître, se montrer;  obéir"),
    array("paro","amo","paraui","paratum","préparer"),
    array("perdo","lego","perdidi","perditum","perdre, ruiner, détruire. Première lettre : p"),
    array("permitto","lego","permisi","permissum","permettre, remettre, abandonner, confier"),
    array("placeo","moneo","placui","placitum","plaire"),
    array("praebeo","moneo","praebui","praebitum","fournir"),
    array("praesto","amo","praestiti","praestitum","être supérieur, dépasser"),
    array("prohibeo","moneo","prohibui","prohibitum","interdire. Première lettre : p"),
    array("prosum","sum","profui","-","être utile. première lettre : p"),
    array("quaero","lego","quaesiui","quaesitum","chercher, demander. Première lettre : q"),
    array("quiesco","lego","quieui","quietum","se reposer, dormir. Première lettre : q"),
    array("recipio","capio","recepi","receptum","reprendre, recevoir ; me - : se retirer"),
    array("reddo","lego","reddidi","redditum","rendre"),
    array("redeo","eo","redii,rediui","reditum","revenir"),
    array("refero","lego","retuli","relatum","rapporter, raconter"),
    array("relinquo","lego","reliqui","relictum","laisser, abandonner"),
    array("respondeo","moneo","respondi","responsum","répondre"),
    array("rumpo","lego","rupi","ruptum","briser, faire éclater ; enfreindre. Première lettre : r"),
    array("scio","audio","sciui","scitum","savoir"),
    array("scribo","lego","scripsi","scriptum","écrire"),
    array("sentio","audio","sensi","sensum","percevoir, s'apercevoir. Première lettre : s"),
    array("soleo","moneo","solitus sum","-","avoir l'habitude"),
    array("specto","amo","spectaui","spectatum","regarder. Première lettre : s"),
    array("spero","amo","speraui","speratum"," espérer"),
    array("statuo","lego","statui","statutum","décider"),
    array("sumo","lego","sumpsi","sumptum","prendre, se saisir de. Première lettre : s"),
    array("taceo","moneo","tacui","tacitum","se taire"),
    array("tango","lego","tetigi","tactum","toucher"),
    array("tego","lego","texi","tectum","couvrir, recouvrir, cacher, abriter, protéger"),
    array("terreo","moneo","terrui","territum","effrayer, épouvanter"),
    array("timeo","moneo","timui","-","craindre. Première lettre : t"),
    array("tollo","lego","sustuli","sublatum","soulever, élever, porter, élever, enlever, supprimer"),
    array("traho","lego","traxi","tractum","tirer, différer, retarder"),
    array("trado","lego","tradidi","traditum","transmettre, livrer"),
    array("ualeo","moneo","ualui","ualitum","avoir de la valeur, être fort"),
    array("ueho","lego","uexi","uectum","transporter"),
    array("uerto","lego","uerti","uersum","tourner, changer, traduire"),
    array("ueto","amo","uetui","uetitum","interdire. Première lettre : u")
);
?>
