<?php
$titre="Les verbes qu'il faut connaître à la fin de la cinquième";
$bini=array(
    array("abeo","eo","abiui,abii","abitum","s'éloigner, partir. Première lettre : a"),
    array("adeo","eo","adii","aditum","aller dans, aller vers, aborder"),
    array("ago","lego","egi","actum","pousser devant soi, faire, traiter, agir"),
    array("amo","amo","amaui","amatum","aimer, être amoureux"),
    array("audio","audio","audiui","auditum","entendre (dire), écouter, apprendre"),
    array("capio","capio","cepi","captum","prendre. Première lettre : c"),
    array("cedo","lego","cessi","cessum","s'éloigner, être inférieur, céder à"),
    array("certo","amo","certaui","certatum","combattre, concourir. Premières lettres : ce"),
    array("cogito","amo","cogitaui","cogitatum","penser, réfléchir"),
    array("colo","lego","colui","cultum","honorer, cultiver, habiter"),
    array("condo","lego","condidi","conditum"," fonder une ville. Première lettre : c"),
    array("credo","lego","credidi","creditum","confier en prêt, croire, avoir confiance"),
    array("curo","amo","curaui","curatum","se charger de, prendre soin de, soigner"),
    array("dico","lego","dixi","dictum","dire"),
    array("do","amo","dedi","datum","donner"),
    array("eo","eo","ii,iui","itum","aller"),
    array("facio","capio","feci","factum","faire"),
    array("fugio","capio","fugi","-","s'enfuir, fuir"),
    array("gero","lego","gessi","gestum","porter, exécuter, faire. Première lettre : g"),
    array("habeo","moneo","habui","habitum","avoir, considérer comme"),
    array("inquit","invaria","-","-","dit-il, dit-elle"),
    array("iubeo","moneo","iussi","iussum","ordonner"),
    array("laudo","amo","laudaui","laudatum","louer, approuver"),
    array("lego","lego","legi","lectum","lire"),
    array("metuo","lego","metui","metutum","craindre. Première lettre : m"),
    array("mitto","lego","misi","missum","envoyer"),
    array("moueo","moneo","moui","motum","déplacer, émouvoir"),
    array("oro","amo","oraui","oratum","prier. Première lettre : o"),
    array("peruenio","audio","perueni","peruentum","parvenir"),
    array("peto","lego","peti,petiui","petitum","chercher à atteindre, attaquer, demander"),
    array("pono","lego","posui","positum","poser, placer"),
    array("possum","sum","potui","-","pouvoir"),
    array("pugno","amo","pugnaui","pugnatum","combattre. Première lettre : p"),
    array("puto","amo","putaui","putatum","penser, supposer"),
    array("rapio","capio","rapui","raptum","ravir, se saisir vivement de"),
    array("rogo","amo","rogaui","rogatum"," demander"),
    array("seruo","amo","seruaui","seruatum","veiller sur, sauver"),
    array("sum","sum","fui","-","être"),
    array("teneo","moneo","tenui","tentum","tenir, retenir, empêcher"),
    array("uenio","audio","ueni","uentum","venir"),
    array("uideo","moneo","uidi","uisum","voir. Au passif : paraître"),
    array("uinco","lego","uici","uictum","vaincre"),
    array("uiuo","lego","uixi","uictum","vivre"),
    array("uoco","amo","uocaui","uocatum","appeler"),
    array("uolo","lego","uolui","-","vouloir"),
);    
?>
